### ISSUE TITLE
Websocket connection start fails with below error log

### ISSUE THREAD

**Issue by dinak1989** [TooTallNate/Java-WebSocket#1040]
System.err: java.net.BindException: bind failed: EADDRINUSE (Address already in use)
2020-06-28 12:25:02.449 2489-5110/com.ticketnew.mpos W/System.err:     at libcore.io.IoBridge.bind(IoBridge.java:99)
2020-06-28 12:25:02.449 2489-5110/com.ticketnew.mpos W/System.err:     at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
2020-06-28 12:25:02.449 2489-5110/com.ticketnew.mpos W/System.err:     at java.net.ServerSocket.bind(ServerSocket.java:336)
2020-06-28 12:25:02.449 2489-5110/com.ticketnew.mpos W/System.err:     at java.net.ServerSocket.bind(ServerSocket.java:296)
2020-06-28 12:25:02.449 2489-5110/com.ticketnew.mpos W/System.err:     at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:508)
2020-06-28 12:25:02.449 2489-5110/com.ticketnew.mpos W/System.err:     at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:316)
2020-06-28 12:25:02.449 2489-5110/com.ticketnew.mpos W/System.err:     at java.lang.Thread.run(Thread.java:818)
2020-06-28 12:25:02.449 2489-5110/com.ticketnew.mpos W/System.err: Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
2020-06-28 12:25:02.450 2489-5110/com.ticketnew.mpos W/System.err:     at libcore.io.Posix.bind(Native Method)
2020-06-28 12:25:02.450 2489-5110/com.ticketnew.mpos W/System.err:     at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
2020-06-28 12:25:02.450 2489-5110/com.ticketnew.mpos W/System.err:     at libcore.io.IoBridge.bind(IoBridge.java:97)

Code Snippet

 InetSocketAddress inetSocketAddress = new InetSocketAddress(host, port);
  webSocketServer = new EDCWebSocketServer(inetSocketAddress);
   webSocketServer.setReuseAddr(true);
   webSocketServer.start();

**Comment by PhilipRoman** [comment]
Does this happen always or just sometimes?
Can you verify that the port isn't used by another process?

**Comment by morsonCoder** [comment]
kill the java application or change the port maybe resolved this problem

**Comment by marci4** [comment]
Closing this issue since there was no example application provided.

Best regards,
Marcel
