### ISSUE TITLE
The client closes connection at 60s after receiving a Control frame.

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [TooTallNate/Java-WebSocket#1059]
**Describe the bug**
Actually, I'm not sure whether it's  client's bug or server's.   
I'm crawling danmuku from douyu(a live stream website <https://www.douyu.com/>). Here are the details.  

+ My websocket client always closed at 60s. Here's the report.
```
org.java_websocket.exceptions.InvalidFrameException: Control frame can't have fin==false set
	at org.java_websocket.framing.ControlFrame.isValid(ControlFrame.java:48)
	at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:517)
	at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:675)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:377)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:217)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:507)
	at java.lang.Thread.run(Thread.java:745)
```

+ After I delete the action throwing `Control frame can't have fin==false set` in [ControlFrame.java](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/framing/ControlFrame.java#L48), the app works fine.

+ A similar python version works fine. I'm sure both implementation logic are the same.
<https://github.com/shuishen49/douyudanmu>

**To Reproduce**
1. Just run the example below.

**Example application to reproduce the issue**
```
import java.io.ByteArrayOutputStream;
import java.net.URI;
import java.nio.ByteBuffer;
import java.util.Map;

import org.java_websocket.client.WebSocketClient;
import org.java_websocket.drafts.Draft;
import org.java_websocket.handshake.ServerHandshake;


public class ExampleClient extends WebSocketClient {

	long tBegin;
	long tEnd;

	public ExampleClient(URI serverUri, Draft draft) {
		super(serverUri, draft);
	}

	public ExampleClient(URI serverURI) {
		super(serverURI);
	}

	public ExampleClient(URI serverUri, Map<String, String> httpHeaders) {
		super(serverUri, httpHeaders);
	}

	@Override
	public void onOpen(ServerHandshake handshakedata) {
		tBegin = System.currentTimeMillis();

		String realRoomId = "312212";
		String loginCMD = String.format(
				"type@=loginreq/roomid@=%s/dfl@=sn@AA=105@ASss@AA=1/username@=%s/uid@=%s/ver@=20190610/aver@=218101901/ct@=0/",
				realRoomId, "99047358", "99047358");
		sendMsg(loginCMD);

		String joinGroupCMD = String.format("type@=joingroup/rid@=%s/gid@=1/", realRoomId);
		sendMsg(joinGroupCMD);

		new Thread(new Runnable() {
			@Override
			public void run() {
				try {
					while (true) {
						String heartBeatCMD = "type@=mrkl/";
						sendMsg(heartBeatCMD);
						Thread.sleep(45000);
					}
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		}).start();
	}

	@Override
	public void onMessage(String message) {
		System.out.println("received: " + message);
	}

	@Override
	public void onMessage(ByteBuffer blob) {
		System.out.println("received: blob");
	}

	@Override
	public void onClose(int code, String reason, boolean remote) {
		tEnd = System.currentTimeMillis();
		System.out.printf("耗时 %d s\r\n", (tEnd - tBegin) / 1000);
	}

	@Override
	public void onError(Exception ex) {
		ex.printStackTrace();
	}

	public static void main(String[] args) throws Exception {
		ExampleClient c = new ExampleClient(new URI("wss://danmuproxy.douyu.com:8501"));
		c.connect();
	}

	/**
	 * 发送数据包
	 * 
	 * @param oper 操作类型
	 * @param data 数据
	 */
	static byte[] bufferSend = new byte[1024];

	private void sendMsg(String data) {
		synchronized (bufferSend) {
			byte[] contents = data.getBytes();
			// 计算消息长度 = 消息长度(4) + 消息类型(2 + 2) + 真实消息内容长度 + 结尾标识长度(1)
			int contenLeng = 4 + 4 + contents.length + 1;

			intToBytesLittle(contenLeng, bufferSend, 0);
			intToBytesLittle(contenLeng, bufferSend, 4);
			intToBytesLittle(689, bufferSend, 8);// 文本格式类型（加密0 + 保留0）
			System.arraycopy(contents, 0, bufferSend, 12, contents.length);
			bufferSend[12 + contents.length] = 0; // 标识数据结尾
			// send(ByteBuffer.wrap(bufferSend, 0, 13 + contents.length));
			// printHexString(bufferSend, 13 + contents.length);

			ByteArrayOutputStream out = new ByteArrayOutputStream(13 + contents.length);
			out.write(bufferSend, 0, 13 + contents.length);
			send(out.toByteArray());
			printHexString(out.toByteArray(), out.toByteArray().length);

		}
	}

	/**
	 * 以小端模式将int转成byte[]
	 *
	 * @param value
	 * @return
	 */
	private static void intToBytesLittle(int value, byte[] src, int offset) {
		src[offset + 3] = (byte) ((value >> 24) & 0xFF);
		src[offset + 2] = (byte) ((value >> 16) & 0xFF);
		src[offset + 1] = (byte) ((value >> 8) & 0xFF);
		src[offset] = (byte) (value & 0xFF);
	}

	/**
	 * 将指定byte数组以16进制的形式打印到控制台
	 *
	 * @param hint String
	 * @param b    byte[]
	 * @return void
	 */
	public static void printHexString(byte[] b, int length) {
		for (int i = 0; i < length; i++) {
			String hex = Integer.toHexString(b[i] & 0xFF);
			if (hex.length() == 1) {
				hex = '0' + hex;
			}
			System.out.print("0x" + hex.toUpperCase());
			if (i != length - 1)
				System.out.print(", ");
		}
		System.out.println("");
	}

}
```

**Expected behavior**
The connection will keep alive for at least 5 min for test.

**Debug log**
The the debug log (set the log level to `TRACE`) to help explain your problem.
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
0x85, 0x00, 0x00, 0x00, 0x85, 0x00, 0x00, 0x00, 0xB1, 0x02, 0x00, 0x00, 0x74, 0x79, 0x70, 0x65, 0x40, 0x3D, 0x6C, 0x6F, 0x67, 0x69, 0x6E, 0x72, 0x65, 0x71, 0x2F, 0x72, 0x6F, 0x6F, 0x6D, 0x69, 0x64, 0x40, 0x3D, 0x33, 0x31, 0x32, 0x32, 0x31, 0x32, 0x2F, 0x64, 0x66, 0x6C, 0x40, 0x3D, 0x73, 0x6E, 0x40, 0x41, 0x41, 0x3D, 0x31, 0x30, 0x35, 0x40, 0x41, 0x53, 0x73, 0x73, 0x40, 0x41, 0x41, 0x3D, 0x31, 0x2F, 0x75, 0x73, 0x65, 0x72, 0x6E, 0x61, 0x6D, 0x65, 0x40, 0x3D, 0x39, 0x39, 0x30, 0x34, 0x37, 0x33, 0x35, 0x38, 0x2F, 0x75, 0x69, 0x64, 0x40, 0x3D, 0x39, 0x39, 0x30, 0x34, 0x37, 0x33, 0x35, 0x38, 0x2F, 0x76, 0x65, 0x72, 0x40, 0x3D, 0x32, 0x30, 0x31, 0x39, 0x30, 0x36, 0x31, 0x30, 0x2F, 0x61, 0x76, 0x65, 0x72, 0x40, 0x3D, 0x32, 0x31, 0x38, 0x31, 0x30, 0x31, 0x39, 0x30, 0x31, 0x2F, 0x63, 0x74, 0x40, 0x3D, 0x30, 0x2F, 0x00
0x2C, 0x00, 0x00, 0x00, 0x2C, 0x00, 0x00, 0x00, 0xB1, 0x02, 0x00, 0x00, 0x74, 0x79, 0x70, 0x65, 0x40, 0x3D, 0x6A, 0x6F, 0x69, 0x6E, 0x67, 0x72, 0x6F, 0x75, 0x70, 0x2F, 0x72, 0x69, 0x64, 0x40, 0x3D, 0x33, 0x31, 0x32, 0x32, 0x31, 0x32, 0x2F, 0x67, 0x69, 0x64, 0x40, 0x3D, 0x31, 0x2F, 0x00
0x14, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00, 0xB1, 0x02, 0x00, 0x00, 0x74, 0x79, 0x70, 0x65, 0x40, 0x3D, 0x6D, 0x72, 0x6B, 0x6C, 0x2F, 0x00
received: blob
received: blob
...
received: blob
0x14, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00, 0xB1, 0x02, 0x00, 0x00, 0x74, 0x79, 0x70, 0x65, 0x40, 0x3D, 0x6D, 0x72, 0x6B, 0x6C, 0x2F, 0x00
received: blob
received: blob
...
received: blob
org.java_websocket.exceptions.InvalidFrameException: Control frame can't have fin==false set
	at org.java_websocket.framing.ControlFrame.isValid(ControlFrame.java:48)
	at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:517)
	at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:675)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:377)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:217)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:507)
	at java.lang.Thread.run(Thread.java:745)
耗时 60 s
```

**Environment(please complete the following information):**
 - Version used: the latest master branch
 - Java version: java_1.8.0_101
 - Operating System and version: Win 10

**Additional context**

**Comment by dota17** [comment]
The exampleCilent received a PONG frame, which is invalid.
I think you can check the server whether it send a valid PONG frame.

**Comment by nICEnnnnnnnLee** [comment]
Hmmmmm... 
Well, it seems the server not implemented standardly, although it appears to work properly in the Chrome/Firefox browser and python websocket Library :scream:

**Comment by marci4** [comment]
@nICEnnnnnnnLee sorry to write after you closed the issue.
I add an additional look at this issue.
It really seems that the pong frame is not correctly implemented by the server.

The ping frame (which requires a pong frame in reponse) is sent to the server since the [lost connection detection](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection) is active by default.
This is the difference to the python websocket library or Chrome/Firefox (but I think Chrome was sending some pings at least for some time).

Check the wiki article on how to disable the feature.

Best regards,
Marcel
