### ISSUE TITLE
Shutdown fails sometimes

### ISSUE THREAD

**Issue by Kaspek2480** [TooTallNate/Java-WebSocket#1075]
Sometimes, when i disable WebSocket because i want to re launch new code, it didn't stop correctly because i'm getting error when i am trying to run my app

```
21:14:47.701 [WebSocketSelector-19] ERROR org.java_websocket.server.WebSocketServer - Shutdown due to fatal error
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:533)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "WebSocketSelector-19" java.lang.NullPointerException
	at xyz.kaspek.kaspekapi.websocket.beta.SimpleServer.onError(SimpleServer.java:192)
	at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:649)
	at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:542)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
	at java.lang.Thread.run(Thread.java:748)
```

Method used to to stop websocket: 
 ```java
WebSocketManager.getSimpleServer().stop();
System.out.println();
System.out.println("Websoket shutdown completed");
System.out.println();
```

Method:
```java
public static SimpleServer getSimpleServer() {
    return simpleServer;
}
```

SimpleServer is class which extends WebSocketServer
```java
public SimpleServer(int port) {
    super(new InetSocketAddress("0.0.0.0", port));
    applySsl(this);
    WebSocketManager.setSimpleServer(this);
}
```

Please tell me what i am doing wrong

**Comment by PhilipRoman** [comment]
Use `server.setReuseAddr(true)` **before** starting it. If you want to know why it's necessary, you can read more here: https://stackoverflow.com/questions/3229860/what-is-the-meaning-of-so-reuseaddr-setsockopt-option-linux

**Comment by Kaspek2480** [comment]
Thanks for help 🤩
