### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by birdhello** [TooTallNate/Java-WebSocket#1098]
你好！

错误日志：
WebSocketServer: Shutdown due to fatal error
    java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:442)
        at sun.nio.ch.Net.bind(Net.java:434)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:224)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:533)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
        at java.lang.Thread.run(Thread.java:764)

问题描述：
在我的 Android 工程中引用了 Java-WebSocket，成功的建立了 WebSocketServer  并且可以和 WebSocketClient 通讯。
当 WebSocketServer 在没有关闭的情况下，我强杀了我的应用，当我再次启动我的程序的时候，发生了上面的错误。

在我看来，进程都被杀死了，理论上不应该发生这个错误，请问有没有解决方案？

谢谢你的阅读！

**Comment by PhilipRoman** [comment]
See https://github.com/TooTallNate/Java-WebSocket/wiki/Enable-SO_REUSEADDR
If the issue persists, provide a minimal example that reproduces it.

**Comment by birdhello** [comment]
> 请参阅https://github.com/TooTallNate/Java-WebSocket/wiki/Enable-SO_REUSEADDR
> 如果问题仍然存在，请提供一个再现该问题的最小示例。

非常感谢你的回复，这个方案完美的解决了我的问题，再次感谢！
