### ISSUE TITLE
setReuseAddr not working

### ISSUE THREAD

**Issue by XJIOP** [TooTallNate/Java-WebSocket#1099]
**Describe the bug**
When trying to reconnect the server always gives an error "Address already in use"

**Example application to reproduce the issue**
```
    private ServerSocket mServerSocket;

    private void connect() {
        try {
            mServerSocket = new ServerSocket(new InetSocketAddress("192.168.1.123", 8765));
            mServerSocket.setReuseAddr(true);
            mServerSocket.setTcpNoDelay(true);
            mServerSocket.setConnectionLostTimeout(30000);
            mServerSocket.start();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void checkConnection() {

        Request request = new Request.Builder().url("ws://192.168.1.123:8765").build();
        OkHttpClient okHttpClient = new OkHttpClient().newBuilder().build();
        okHttpClient.newWebSocket(request, new WebSocketListener() {

            @Override
            public void onOpen(@NotNull okhttp3.WebSocket webSocket, @NotNull Response response) {
                super.onOpen(webSocket, response);
            }

            @Override
            public void onClosed(@NotNull okhttp3.WebSocket webSocket, int code, @NotNull String reason) {
                super.onClosed(webSocket, code, reason);
            }

            @Override
            public void onClosing(@NotNull okhttp3.WebSocket webSocket, int code, @NotNull String reason) {
                super.onClosing(webSocket, code, reason);

                webSocket.close(code, reason);
            }

            @Override
            public void onFailure(@NotNull okhttp3.WebSocket webSocket, @NotNull Throwable t, @Nullable Response response) {
                super.onFailure(webSocket, t, response);

                try {
                    if(mServerSocket != null)
                        mServerSocket.stop();
                }
                catch (Exception e) {
                    e.printStackTrace();
                }

                connect();
            }
        });

        okHttpClient.dispatcher().executorService().shutdown();
    } 

    public class ServerSocket extends WebSocketServer {

        public ServerSocket(InetSocketAddress address) {
            super(address);
        }

        @Override
        public void onOpen(WebSocket conn, ClientHandshake handshake) {}

        @Override
        public void onClose(WebSocket conn, int code, String reason, boolean remote) {}

        @Override
        public void onMessage(WebSocket conn, String message) {}

        @Override
        public void onError(WebSocket conn, Exception ex) {
            ex.printStackTrace();
        }

        @Override
        public void onStart() {
            checkConnection();
        }
    }
```

**Debug log**

catch start
```
2020-11-26 16:42:15.711 13416-13519/testserver W/System.err: [WebSocketSelector-17359] ERROR org.java_websocket.server.WebSocketServer - Shutdown due to fatal error
2020-11-26 16:42:15.711 13416-13519/testserver W/System.err: java.net.BindException: Address already in use
2020-11-26 16:42:15.711 13416-13519/testserver W/System.err:     at sun.nio.ch.Net.bind0(Native Method)
2020-11-26 16:42:15.711 13416-13519/testserver W/System.err:     at sun.nio.ch.Net.bind(Net.java:442)
2020-11-26 16:42:15.711 13416-13519/testserver W/System.err:     at sun.nio.ch.Net.bind(Net.java:434)
2020-11-26 16:42:15.711 13416-13519/testserver W/System.err:     at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:533)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

ServerSocket onError
```
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err: java.net.BindException: Address already in use
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at sun.nio.ch.Net.bind0(Native Method)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at sun.nio.ch.Net.bind(Net.java:442)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at sun.nio.ch.Net.bind(Net.java:434)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:533)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
2020-11-26 16:42:15.712 13416-13519/testserver W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

**Environment(please complete the following information):**
 - Version used: 1.5.1
 - Operating System and version: Android 10

**Additional context**
I tried add interval 120 seconds before call connect(), but it does not help.

**Comment by XJIOP** [comment]
Ok, I found issues, it caused by okHttpClient websocket client. But it is not clear why client bind socket.

**Comment by marci4** [comment]
Both okHttp and Java-Websocket use the same port

**Comment by XJIOP** [comment]
> Both okHttp and Java-Websocket use the same port

okHttp is a WebSocket client, it doesn't need to bind the port. This example works perfectly, the problem was that before starting the new server socket, the old server socket was open.
