### ISSUE TITLE
Deadlock during close connection

### ISSUE THREAD

**Issue by pakskiy** [TooTallNate/Java-WebSocket#1101]
**Describe the bug**
Hello! Caught deadlock when closing clients connections. Help me figure out where I misdesigned? Thread that stops the server. 
Thanks!

**To Reproduce**
The problem is rarely reproduced when one client connection is closed by "ping-pong" timeout (**WebSocketTimer**), and second client connection - through the **close()** method:
1) First client connection is closed by "ping-pong" timeout
2) Second client connection is closed through the **close()** method (ws.close())

**Example application to reproduce the issue**
Need some time to to extract the code from the project

**Expected behavior**
Expected closing both clients connections

**Debug log**

**Java stack information for the threads listed above:**

 ```
"WebSocketTimer":
        at chatserver.connection.ConnectionManager.close(ConnectionManager.java:226)
        - waiting to lock <0x00000005d502d9d8> (a chatserver.connection.ConnectionManager)
        at chatserver.server.Server.onClose(Server.java:57)
        at org.java_websocket.server.WebSocketServer.onWebsocketClose(WebSocketServer.java:595)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:504)
        - locked <0x000000072d89bf78> (a org.java_websocket.WebSocketImpl)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:526)
        at org.java_websocket.AbstractWebSocket$1.run(AbstractWebSocket.java:176)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

"WebSocketSelector-28":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000072d84a3a0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at chatserver.connection.Connection.userId(Connection.java:198)
        at chatserver.connection.ConnectionManager.close(ConnectionManager.java:234)
        at chatserver.connection.ConnectionManager.close(ConnectionManager.java:226)
        - locked <0x00000005d502d9d8> (a chatserver.connection.ConnectionManager)
        at chatserver.server.Server.onClose(Server.java:57)
        at org.java_websocket.server.WebSocketServer.onWebsocketClose(WebSocketServer.java:595)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:504)
        - locked <0x000000072d89b740> (a org.java_websocket.WebSocketImpl)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:515)
        at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:563)
        at org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:42)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:406)
        at java.lang.Thread.run(Thread.java:748)

"pool-3-thread-1":
        at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:416)
        - waiting to lock <0x000000072d89b740> (a org.java_websocket.WebSocketImpl)
        at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:569)
        at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:773)
        at chatserver.connection.ConnectionImpl.close(ConnectionImpl.java:75)
        at chatserver.connection.Connection.closeConnection(Connection.java:287)
        at chatserver.connection.Connection.close(Connection.java:281)
        at chatserver.connection.ConnectionManager.close(ConnectionManager.java:242)
        at chatserver.module.AuthModule.handleAuthorizeTimeout(AuthModule.java:369)
        at chatserver.module.AuthModule.lambda$startAuthorizeTimeout$0(AuthModule.java:344)
        at chatserver.module.AuthModule$$Lambda$223/1525843693.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.
```

**Environment(please complete the following information):**
 - Version used: 1.3.9
 - Java version: 1.8.222
 - Operating System and version: CentOS

**Comment by marci4** [comment]
Hello @pakskiy 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by pakskiy** [comment]
Hello @marci4 !

Modified the post according to the template. The only thing is, I can't quickly download the project code now. It takes time! Thanks!

**Comment by marci4** [comment]
@pakskiy please ping me when you updated the template!
