### ISSUE TITLE
Handshake Failed between Two Android devices

### ISSUE THREAD

**Issue by mingway426** [TooTallNate/Java-WebSocket#1153]
Hi there，I'm using this library to create a SSL websocket communications between two android devices，but i got the exception infomation as below:

`
2021-05-21 14:16:36.411 18181-18545/com.mingway.websocketclienttest I/System.out: [socket] connection /192.168.1.105:50188;LocalPort=-1(0)
2021-05-21 14:16:36.882 18181-18545/com.mingway.websocketclienttest W/System.err: javax.net.ssl.SSLHandshakeException: Connection closed by peer
2021-05-21 14:16:36.883 18181-18545/com.mingway.websocketclienttest W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2021-05-21 14:16:36.883 18181-18545/com.mingway.websocketclienttest W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
2021-05-21 14:16:36.883 18181-18545/com.mingway.websocketclienttest W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
2021-05-21 14:16:36.883 18181-18545/com.mingway.websocketclienttest W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(ConscryptFileDescriptorSocket.java:473)
2021-05-21 14:16:36.884 18181-18545/com.mingway.websocketclienttest W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getInputStream(ConscryptFileDescriptorSocket.java:436)
2021-05-21 14:16:36.884 18181-18545/com.mingway.websocketclienttest W/System.err:     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:479)
2021-05-21 14:16:36.884 18181-18545/com.mingway.websocketclienttest W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-05-21 14:16:36.884 18181-18545/com.mingway.websocketclienttest I/System.out: Disconnected
`

I created the trustStore file and keystore with this article: https://callistaenterprise.se/blogg/teknik/2011/11/24/creating-self-signed-certificates-for-use-on-android

and my test code is that:

**Server SSL factory**

`public static void configTSLConfiguration(WebSocketServer server, Context context) {
        try {
            KeyStore ks = KeyStore.getInstance("BKS");
            InputStream inputStream = context.getResources().openRawResource(R.raw.server);
            ks.load(inputStream, storePassword.toCharArray());
            KeyManagerFactory kmf = KeyManagerFactory.getInstance("X509");
            kmf.init(ks, keyPassword.toCharArray());

            KeyStore ts = KeyStore.getInstance("BKS");
            InputStream tsInputstream = context.getResources().openRawResource(R.raw.servicetruststore);
            ks.load(tsInputstream, storePassword.toCharArray());
            TrustManagerFactory tmf = TrustManagerFactory.getInstance("X509");
            tmf.init(ts);

            SSLContext sslContext = SSLContext.getInstance("SSL");
            sslContext.init(kmf.getKeyManagers(), tmf.getTrustManagers(), null);
            //Lets remove some ciphers and protocols
            SSLEngine engine = sslContext.createSSLEngine();
            List<String> ciphers = new ArrayList<String>(Arrays.asList(engine.getEnabledCipherSuites()));
            ciphers.remove("TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256");
            List<String> protocols = new ArrayList<String>(Arrays.asList(engine.getEnabledProtocols()));
            protocols.remove("SSLv3");

            CustomSSLWebSocketServerFactory factory = new CustomSSLWebSocketServerFactory(sslContext,
                    protocols.toArray(new String[]{}), ciphers.toArray(new String[]{}));

            server.setWebSocketFactory(factory);
        } catch (Exception e){
            IpqLogic.logd(TAG,"TSL Exception:" + e.getMessage());
        }`

**Client SSLFactory**

`val address = "wss://$host:$port"
        var uri = URI.create(address)

        var service = JavaWebsocketSimple(uri)

        val ks = KeyStore.getInstance("BKS")
        val inputStream: InputStream = resources.openRawResource(R.raw.client)
        ks.load(inputStream,password.toCharArray())
        val kmf =
            KeyManagerFactory.getInstance("X509")
        kmf.init(ks, password.toCharArray())

        val ts = KeyStore.getInstance("BKS")
        val tsInputstream: InputStream =
                resources.openRawResource(R.raw.clienttruststore)
        ks.load(tsInputstream, password.toCharArray())
        val tmf =
            TrustManagerFactory.getInstance("X509")
        tmf.init(ts)

        val sslContext = SSLContext.getInstance("SSL")
        sslContext.init(kmf.keyManagers, tmf.trustManagers, null)
        
        val factory: SSLSocketFactory = sslContext
            .socketFactory

        service.setSocketFactory(factory)

        service.connectBlocking()`

the communication without SSL Certification is OK.

the problem interrupt my project for several days，any suggestions are greate，thks

**Comment by marci4** [comment]
Looks like a certificate handshake error, not a websocket error.

Please redirect your question e.g. to stackoverflow.

Best regards,
Marcel
