### ISSUE TITLE
Android 8 / ssl == null

### ISSUE THREAD

**Issue by anthonydelahoz** [TooTallNate/Java-WebSocket#1161]
I have an issue that i can reproduce only with Android 8.1.0
Using org.java-websocket:Java-WebSocket:1.5.2 (same thing with 1.5.1)

When i want to close a WSS connection using `webSocket.close(GOING_AWAY_CLOSURE_STATUS, "force_close");`, i have onError called with an Exception :

```
2021-06-25 15:53:38.073 21257-21257/com.abill D/MultiPosServerService: logout
2021-06-25 15:53:38.073 21257-21257/com.abill D/MultiPosServerService: WebSocket close 1001
2021-06-25 15:53:38.083 21257-21389/com.abill E/MyWebSocketServer: onError() is called
2021-06-25 15:53:38.083 21257-21389/com.abill W/System.err: java.lang.NullPointerException: ssl == null
2021-06-25 15:53:38.084 21257-21389/com.abill W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_set_timeout(Native Method)
2021-06-25 15:53:38.084 21257-21389/com.abill W/System.err:     at com.android.org.conscrypt.SslWrapper.setTimeout(SslWrapper.java:101)
2021-06-25 15:53:38.084 21257-21389/com.abill W/System.err:     at com.android.org.conscrypt.ActiveSession.invalidate(ActiveSession.java:147)
2021-06-25 15:53:38.084 21257-21389/com.abill W/System.err:     at com.android.org.conscrypt.DelegatingExtendedSSLSession.invalidate(DelegatingExtendedSSLSession.java:120)
2021-06-25 15:53:38.085 21257-21389/com.abill W/System.err:     at org.java_websocket.SSLSocketChannel2.close(SSLSocketChannel2.java:387)
2021-06-25 15:53:38.085 21257-21389/com.abill W/System.err:     at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:541)
2021-06-25 15:53:38.085 21257-21389/com.abill W/System.err:     at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:572)
2021-06-25 15:53:38.085 21257-21389/com.abill W/System.err:     at org.java_websocket.SocketChannelIOHelper.batch(SocketChannelIOHelper.java:112)
2021-06-25 15:53:38.085 21257-21389/com.abill W/System.err:     at org.java_websocket.server.WebSocketServer.doWrite(WebSocketServer.java:541)
2021-06-25 15:53:38.086 21257-21389/com.abill W/System.err:     at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:398)
2021-06-25 15:53:38.086 21257-21389/com.abill W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-06-25 15:53:38.086 21257-21389/com.abill E/MyWebSocketServer: Exception ssl == null
```

Second issue : _onClose_ is not called after _onError_.

Important to know : My SSL socket have been correctly been initialized, i succeeded to exchange datas before calling _socket.close._
I succeeded to correct the problem by adding a try / catch NullPointerException around the `invalidate `method on _org.java_websocket.SSLSocketChannel2.close_

**Comment by marci4** [comment]
Seems to be an issue with https://github.com/google/conscrypt and therefore out of scope.
Sorry not much I can do here.

Please raise an issue there.
Best regards,
Marcel
