### ISSUE TITLE
A “Connection refused” error occurs when running tests

### ISSUE THREAD

**Issue by shanto-Rahman** [TooTallNate/Java-WebSocket#1175]
**Describe the bug**
“Connection Refused” problem occurs when running tests. I ran “mvn test –Dtest=Issue256Test” and the first test run in the test class always fails. The error is “java.net.ConnectionException: Connection refused”.  

**To Reproduce**
1. mvn test –Dtest=Issue256Test 

**Example application to reproduce the issue**
A link to a github project/gist to reproduce the issue.

git clone https://github.com/TooTallNate/Java-WebSocket.git; git checkout fa3909c391195178ccf5a92d4ac342a30ae247c8;
mvn test –Dtest=Issue256Test

**Expected behavior**
Tests should not fail due to “Connection refused

**Debug log**
The the debug log (set the log level to `TRACE`) to help explain your problem.

Running org.java_websocket.issues.Issue256Test
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.Socket.connect(Socket.java:607)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:388)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "WebSocketConnectReadThread-36" org.junit.internal.AssumptionViolatedException: got: <true>, expected: is <false>
        at org.junit.Assume.assumeThat(Assume.java:95)
        at org.java_websocket.issues.Issue256Test$2.onError(Issue256Test.java:113)
        at org.java_websocket.client.WebSocketClient.onWebsocketError(WebSocketClient.java:529)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:405)
        at java.lang.Thread.run(Thread.java:748)
Tests run: 20, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.4 sec <<< FAILURE!
runReconnectScenario0(org.java_websocket.issues.Issue256Test)  Time elapsed: 5.015 sec  <<< ERROR!

**Environment(please complete the following information):**
 - Version used: fa3909c391195178ccf5a92d4ac342a30ae247c8
 - Java version: openjdk version "1.8.0_292"
 - Operating System and version: OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)

**Comment by PhilipRoman** [comment]
This issue is about an old version and has been fixed in 934bd9f. If it still happens on latest version, open a new issue.
