### ISSUE TITLE
can't create websocket client

### ISSUE THREAD

**Issue by khordady** [TooTallNate/Java-WebSocket#1177]
**Describe the bug**
I can't create Websocketclient object at all;

**To Reproduce**
WebSOClient webSOClient= new WebSOClient(new URI(server+"?token="+token+"&connectId=12345"));

**Debug log**
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.java_websocket.drafts.Draft_6455.<init>(Draft_6455.java:113)
	at org.java_websocket.drafts.Draft_6455.<init>(Draft_6455.java:200)
	at org.java_websocket.drafts.Draft_6455.<init>(Draft_6455.java:188)
	at org.java_websocket.drafts.Draft_6455.<init>(Draft_6455.java:168)
	at org.java_websocket.client.WebSocketClient.<init>(WebSocketClient.java:160)
	at sample.WebSOClient.<init>(WebSOClient.java:13)
	at sample.WebSocketImpl$GetToken.run(WebSocketImpl.java:59)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 7 more

i use that uri in another app-language and it works great. I am new at java and websocket

**Environment(please complete the following information):**
 - Version used: 1.5.2
 - Java version: 16
 - Operating System and version: win 10

**Additional context**
public class WebSOClient extends WebSocketClient {

    public WebSOClient(URI serverURI) {
        super(serverURI);
    }

    public WebSOClient(URI serverUri, Draft draft) {
        super(serverUri, draft);
    }

    @Override
    public void onOpen(ServerHandshake handshakedata) {
        send("Hello, it is me. Mario :)");
        System.out.println("new connection opened");
    }

    @Override
    public void onClose(int code, String reason, boolean remote) {
        System.out.println("closed with exit code " + code + " additional info: " + reason);
    }

    @Override
    public void onMessage(String message) {
        System.out.println("received message: " + message);
    }

    @Override
    public void onMessage(ByteBuffer message) {
        System.out.println("received ByteBuffer");
    }

    @Override
    public void onError(Exception ex) {
        System.err.println("an error occurred:" + ex);
    }
}

**Comment by PhilipRoman** [comment]
This library depends on slf4j-api.
See https://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.25 for more information.
