### ISSUE TITLE
client/server  wss mutual -  problem unwrapping net record

### ISSUE THREAD

**Issue by marcoberri** [TooTallNate/Java-WebSocket#1213]
Hi,
I have  web socket server with mutual auth like:

 ```
      final String STORE_TYPE = environment.getProperty("server.ssl.key-store-type");
        final String STORE_PASSWORD = environment.getProperty("server.ssl.key-store-password");
        final String KEY_PASSWORD = environment.getProperty("server.ssl.key-password");

        KeyStore ks = KeyStore.getInstance(STORE_TYPE);
        File kf = resourceLoader.getResource(environment.getProperty("server.ssl.key-store")).getFile();
        ks.load(new FileInputStream(kf), STORE_PASSWORD.toCharArray());

        KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");
        kmf.init(ks, KEY_PASSWORD.toCharArray());
        TrustManagerFactory tmf = TrustManagerFactory.getInstance("SunX509");
        tmf.init(ks);

        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(kmf.getKeyManagers(), tmf.getTrustManagers(), null);


        SSLParameters sslParameters = new SSLParameters();

        sslParameters.setNeedClientAuth(true);
        sslParameters.setProtocols(new String[]{"TLSv1.1", "TLSv1.2", "TLSv1.3"});

        webSocketServerAction.setWebSocketFactory(new SSLParametersWebSocketServerFactory(sslContext, sslParameters));
         webSocketServerAction.getEndpoints().put( 
        etc.
        etc.
        etc.

```

client:

```
        KeyStore ks = KeyStore.getInstance(config.getStoreType());
        File keyStoreFile = config.getKeyStoreFile();
        ks.load(new FileInputStream(keyStoreFile), config.getStorePassword().toCharArray());

        KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");
        KeyStore kms = KeyStore.getInstance(config.getKeyStoreType());
        File storeFile = config.getKeyStoreFile();
        kms.load(new FileInputStream(storeFile), config.getKeyStorePassword().toCharArray());
        kmf.init(kms, config.getKeyStorePassword().toCharArray());

        TrustManagerFactory tmf = TrustManagerFactory.getInstance("SunX509");
        tmf.init(ks);

        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(kmf.getKeyManagers(), tmf.getTrustManagers(), null);

        SSLParameters sslParameters = new SSLParameters();
        // This is all we need
        sslParameters.setNeedClientAuth(true);

        sslParameters.setProtocols(new String[]{"TLSv1.1", "TLSv1.2", "TLSv1.3"});
        SSLSocketFactory factory = sslContext.getSocketFactory();
        webSocketClientInternal.setSocketFactory(factory);
        webSocketClientInternal.setConnectionLostTimeout(config.getConnectionLostTimeout());
        etc.etc.etc
```

server debug:

```
11:30:59.084 [WebSocketWorker-132] INFO  i.e.s.websocket.TestSocketServer - wss /logbookEvents to client : 151
javax.net.ssl|DEBUG|8B|WebSocketSelector-139|2022-01-19 11:30:59.084 CET|SSLEngineOutputRecord.java:266|WRITE: TLS13 application_data, length = 600
Provider: Cipher.AES/GCM/NoPadding encryption algorithm from: SunJCE
javax.net.ssl|DEBUG|8B|WebSocketSelector-139|2022-01-19 11:30:59.085 CET|SSLCipher.java:2062|Plaintext before ENCRYPTION (
  0000: 81 7E 02 54 7B 0D 0A 20   20 22 69 64 22 3A 20 22  ...T...  "id": "
  0010: 36 31 38 32 37 31 31 65   62 32 64 34 63 31 31 33  6182711eb2d4c113
  0020: 33 39 34 65 65 63 65 33   22 2C 0D 0A 20 20 22 6D  394eece3",..  "m
  0030: 65 73 73 61 67 65 4B 65   79 22 3A 20 22 73 70 61  essageKey": "spa
  0040: 63 65 6F 70 73 2E 67 61   74 65 77 61 79 64 65 73  ceops.gatewaydes
  0050: 69 67 6E 65 72 2E 61 74   74 65 6E 75 61 74 69 6F  igner.attenuatio
etc.etc.
```

client debug :
```

javax.net.ssl|ERROR|1B|qtp365744276-27|2022-01-19 10:24:40.064 UTC|TransportContext.java:341|Fatal (INTERNAL_ERROR): problem unwrapping net record (
"throwable" : {
  javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
  	at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:146)
  	at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:64)
  	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:557)
  	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
  	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
  	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
  	at org.eclipse.jetty.io.ssl.SslConnection.unwrap(SslConnection.java:429)
  	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:718)
  	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:350)
  	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
  	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
  	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
  	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
  	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
  	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
  	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
  	at java.base/java.lang.Thread.run(Thread.java:829)}

)
javax.net.ssl|WARNING|1B|qtp365744276-27|2022-01-19 10:24:40.064 UTC|SSLEngineOutputRecord.java:168|outbound has closed, ignore outbound application data
```

thanx!

**Comment by marci4** [comment]
No WSS?

**Comment by marcoberri** [comment]
it's just a warning, the application works correctly thanks.
