### ISSUE TITLE
I tried to imitate the simple example from the wiki, but it gives an error!

### ISSUE THREAD

**Issue by WenisOK** [TooTallNate/Java-WebSocket#1224]
The  wiki address: https://github.com/TooTallNate/Java-WebSocket/wiki#server-example  
My java code: 
```java
package cn.wjchome.websocket;

import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

import java.net.InetSocketAddress;

public class Server extends WebSocketServer {
    public Server(InetSocketAddress address) {
        super(address);
    }
    @Override
    public void onOpen(WebSocket webSocket, ClientHandshake clientHandshake) {

    }

    @Override
    public void onClose(WebSocket webSocket, int i, String s, boolean b) {

    }

    @Override
    public void onMessage(WebSocket webSocket, String s) {

    }

    @Override
    public void onError(WebSocket webSocket, Exception e) {

    }

    @Override
    public void onStart() {

    }

    public static void main(String[] args) {
        String host = "127.0.0.1";
        int port = 80;
        WebSocketServer server = new Server(new InetSocketAddress(host,port));
        server.run();
    }
}

```
Then I try to execute this code, but the console throws an error!
```shell
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.java_websocket.AbstractWebSocket.<init>(AbstractWebSocket.java:50)
	at org.java_websocket.server.WebSocketServer.<init>(WebSocketServer.java:208)
	at org.java_websocket.server.WebSocketServer.<init>(WebSocketServer.java:181)
	at org.java_websocket.server.WebSocketServer.<init>(WebSocketServer.java:149)
	at cn.wjchome.websocket.Server.<init>(Server.java:11)
	at cn.wjchome.websocket.Server.main(Server.java:41)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 6 more
```

**Comment by WenisOK** [comment]
Also, I downloaded the java-websocket.jar and import in my project library

**Comment by PhilipRoman** [comment]
Java-WebSocket has one dependency which you also need to download: [slf4j-api](https://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.25)
