### ISSUE TITLE
onOpen and WebsocketNotConnectedException

### ISSUE THREAD

**Issue by lgbm** [TooTallNate/Java-WebSocket#1242]
Hello there!

I'm getting a random error in "onOpen" WebSocket Server method.
Basically:

	@Override
	public void onOpen(WebSocket conn, ClientHandshake handshake) {
		...
		conn.send(jsonObject.toString()); <<<< line 97
		...
	}

04/05/2022 16:18:05 - Exception: org.java_websocket.exceptions.WebsocketNotConnectedException
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:673)
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:649)
	at xxx.xxxxxxxxxx.remoting.WSServer.onOpen(WSServer.java:97)
	at org.java_websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:724)
	at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:766)
	at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:307)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:236)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1114)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1086)

My question is: regarding "onOpen" cover, some WebSocket might not be open yet? As said, is small random errors.

Regards,

**Comment by marci4** [comment]
Hello @lgbm

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by lgbm** [comment]
Hello @marci4, regarding WebsocketNotConnectedException into onOpen, may something early instance and validation cre
