### ISSUE TITLE
UnsupportedClassVersionError when compiled against Java 7

### ISSUE THREAD

**Issue by brlnguy** [TooTallNate/Java-WebSocket#125]
When I compile the sources on the _v1.0.0-alpha1_ tag using the Java 6 compiler, everythin works fine. If I use the Java 7 compiler instead, I get the following exception on runtime:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/java_websocket/WebSocketServer : Unsupported major.minor version 51.0
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
  at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
  at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
  at coltram.proto.ui.SwingApplication.<init>(SwingApplication.java:83)
  at coltram.proto.ui.SwingApplication.main(SwingApplication.java:47)
```

The line in question (SwingApplication.java:83) is

```
WSServer server = new WSServer();
```

with

```
class WSServer extends WebSocketServer
```

This exception is reliably reproducable on my system and appears if I switch my Java version from 6 to 7.

This might help http://www.oracle.com/technetwork/java/javase/compatibility-417013.html#incompatibilities.

**Comment by marci4** [comment]
Closing this issue.

It is working for me without any problems!
Greetings
marci4
