### ISSUE TITLE
client send data to server got "more than 125 octets"

### ISSUE THREAD

**Issue by xinguangduan** [TooTallNate/Java-WebSocket#1261]
**Describe what you would like to know or do**
Occasionally, an error occurs (more than 125 octets) when the client sends data to the server 
**Describe the solution you'd considered**
how to avoid it?
**Additional context**
Our scenario is the transmission of binary voice data through websocket

**Comment by marci4** [comment]
Please provide StR

**Comment by xinguangduan** [comment]
2022-07-17 22:29:17.696 ERROR [WebSocketConnectReadThread-2409] o.j.WebSocketImpl 410 - Closing due to invalid data in frame
org.java_websocket.exceptions.InvalidFrameException: more than 125 octets
        at org.java_websocket.drafts.Draft_6455.translateSingleFramePayloadLength(Draft_6455.java:619)
        at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:547)
        at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:762)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:398)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
        at java.lang.Thread.run(Thread.java:748)

**Comment by PhilipRoman** [comment]
It would be helpful if you could post the code that sends the data. If you can, dump the data with wireshark (without using SSL encryption) during the error so that we can see the problematic frame.

**Comment by marci4** [comment]
No StR
