### ISSUE TITLE
org.java_websocket.exceptions.InvalidFrameException：bad rsv 4

### ISSUE THREAD

**Issue by Eucalyptus-fructicetorum** [TooTallNate/Java-WebSocket#1270]
How to solve this
org.java_websocket.exceptions.InvalidFrameException: bad rsv 4
	at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:309)
	at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:286)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:312)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:748)

**Comment by marci4** [comment]
Please update to the latest version and if the issue still persists provide clear steps to repeat.

**Comment by Eucalyptus-fructicetorum** [comment]
Updated to the latest version，Draft_6455 It doesn't meet my needs，Unable to establish a connection with the other party's service, refuses to shake hands，Can you add a wechat or QQ chat

**Comment by Eucalyptus-fructicetorum** [comment]
I just tried the latest version and found that the URL can be escaped to get the information. Otherwise, or ENCODE will report an error

**Comment by marci4** [comment]
Well then the other party is not a websocket server.

Please provide steps to repeat!

**Comment by Eucalyptus-fructicetorum** [comment]
client =  new WebSocketClient(new URI(wsUrl), new Draft_6455(), headerMap, 10000){}

**Comment by NoahAndrews** [comment]
That's not very helpful without access to the server or its source code (or at least more details).

One possibility is that the server is using socket.io, which is not compatible with direct WebSocket clients.
