### ISSUE TITLE
got more than 125 octets errors

### ISSUE THREAD

**Issue by xinguangduan** [TooTallNate/Java-WebSocket#1273]
**Describe what you would like to know or do**
when I use Java-WebSocket as a client to call websocekt server(based Java-WebSocket), got "org.java_websocket.exceptions.InvalidFrameException: more than 125 octets"
Why does this error occur? How to avoid?

Release 1.5.3

**Describe the solution you'd considered**

**Additional context**
Add any other context or links about the question here.

2022-06-18 20:47:25.701 ERROR [WebSocketConnectReadThread-4101709] org.java_websocket.WebSocketImpl 410 - Closing due to invalid data in frame
org.java_websocket.exceptions.InvalidFrameException: more than 125 octets
	at org.java_websocket.drafts.Draft_6455.translateSingleFramePayloadLength(Draft_6455.java:596)
	at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:536)
	at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:739)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:398)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xinguangduan** [comment]
It just a normal usage, as a websocket client.

final WebSocketClient client = new WebSocketClient(new URI(url), new Draft_6455(), headers, 5000) {
    @Override
    public void onOpen(ServerHandshake handShakeData) {
        log.debug("connected to engine, {}", keyInfo);
    }

    @Override
    public void onMessage(String message) {
        JSONObject m = JSON.parseObject(message);

        callback.onMessageFromEngineServer(bizContext.getCid(), bizContext.getDid(), m);
    }

    @Override
    public void onClose(int code, String reason, boolean remote) {
        log.info("received close message from server, {}, code:{}, reason:{}, remote:{}", keyInfo, code, reason, remote);
        callback.onCloseFromEngineServer(bizContext.getCid(), bizContext.getDid(), reason, code, remote);
    }

    **@Override
    public void onError(Exception ex) {
        log.error("received onError from engine. {}, reason:{}.", keyInfo, ex.getMessage());
        callback.onErrorFromEngineServer(bizContext.getCid(), bizContext.getDid(), ex);
    }**
};
client.connectBlocking();

**Comment by marci4** [comment]
Without any additional I would say this issue is not related to the library and is caused by the other endpoint.
