### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.close()' 

### ISSUE THREAD

**Issue by 18722650553** [TooTallNate/Java-WebSocket#1279]
FATAL EXCEPTION: WebSocketWriteThread-119
                                                                                                    Process: com.bitforex.bitforex, PID: 4579
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference
                                                                                                    	at org.java_websocket.client.WebSocketClient$WebsocketWriteThread.closeSocket(WebSocketClient.java:835)
                                                                                                    	at org.java_websocket.client.WebSocketClient$WebsocketWriteThread.run(WebSocketClient.java:803)
                                                                                                    	at java.lang.Thread.run(Thread.java:761)

**Comment by marci4** [comment]
Hello @18722650553 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4
