### ISSUE TITLE
 NullPointerException due to different thread interleaving

### ISSUE THREAD

**Issue by Alisha-R** [TooTallNate/Java-WebSocket#1285]
Commit version- aad66547

Describe the bug
It is possible to encounter a NullPointerException due to a thread interleaving where one thread reads from shared variable connectReadThread after setting a new object (Line 349), but another thread sets connectReadThread to null (Line 526). I can observe such an execution that results in the exception from running an existing test org.java_websocket.issues.Issue256Test with some added delay just before Line 349 of WebSocketClient, resulting in the following stack trace.

Debug log
Running org.java_websocket.issues.Issue256Test
java.lang.NullPointerException
        at org.java_websocket.client.WebSocketClient.reset(WebSocketClient.java:352)
        at org.java_websocket.client.WebSocketClient.reconnectBlocking(WebSocketClient.java:327)
        at org.java_websocket.issues.Issue256Test.runTestScenarioReconnect(Issue256Test.java:136)
        at org.java_websocket.issues.Issue256Test.runReconnectCloseBlocking(Issue256Test.java:161)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:750)

Results :

Failed tests: Tests run: 20, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 6.573 sec <<< FAILURE!
runReconnectCloseBlocking[4](org.java_websocket.issues.Issue256Test)  Time elapsed: 5.014 sec  <<< ERROR!

Tests in error: 
runReconnectCloseBlocking[4](org.java_websocket.issues.Issue256Test): test timed out after 5000 milliseconds

Tests run: 20, Failures: 0, Errors: 1, Skipped: 1

To Reproduce

    Add Thread.sleep(1000) before Line 349
    Run mvn test -Dtest=org.java_websocket.issues.Issue256Test -Dcheckstyle.skip

Expected behavior

    Null Pointer Exception and test failure should not occur

Additional context
When I investigated the WebSocketClient class, I find connectReadThread is a shared variable that is used on Line 349 and Line 526. By injecting a delay before Line Line 349 of WebSocketClient.java, I could get a different thread interleaving where the variable is set to null on Line 526 before the variable is used on Line 349. As a result, the execution throws a NullPointerException.

Environment(please complete the following information):
I ran the test on an Ubuntu 20.04 LTS machine using OpenJDK 1.8.0_312.

**Comment by marci4** [comment]
Duplicates #1282
