### ISSUE TITLE
wss connection(android only)

### ISSUE THREAD

**Issue by unit51** [TooTallNate/Java-WebSocket#141]
When i try to connect to a ssl websocket server i get the following exception on android 

org.apache.harmony.xnet.provider.jsse.OpenSSLSessionImpl cannot be cast to org.apache.harmony.xnet.provider.jsse.SSLSessionImpl

What does this mean?

Thanks!

**Comment by douglasjunior** [comment]
I could make it work!

I created my `SSLContext` in `MyApplication` class.

Like this:
```java
public class MyApplication extends Application {

    private static SSLContext sc;

    static {
        TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
            public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                return new java.security.cert.X509Certificate[]{};
            }

            public void checkClientTrusted(X509Certificate[] chain,
                                           String authType) throws CertificateException {
            }

            public void checkServerTrusted(X509Certificate[] chain,
                                           String authType) throws CertificateException {
            }
        }};

        KeyManager[] keyManager = null;
        try {
            final KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
            KeyManagerFactory factory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            factory.init(keyStore, null);
            keyManager = factory.getKeyManagers();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (UnrecoverableKeyException e) {
            e.printStackTrace();
        } catch (KeyStoreException e) {
            e.printStackTrace();
        }

        try {
            sc = SSLContext.getInstance("TLS");
            sc.init(keyManager, trustAllCerts, new java.security.SecureRandom());
            HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static SSLContext getSSLContext() {
        return sc;
    }
}
```
And when creating my `WebSocketClient`:
```java
            Log.i("Websocket", "Instanciando websocket");
            URI uri;
            try {
                uri = new URI("wss://192.168.254.105:8181/SaframaxWebManager/testeSocket");
            } catch (URISyntaxException e) {
                e.printStackTrace();
                return;
            }

            mWebSocketClient = new WebSocketClient(uri, new Draft_17()) {

                @Override
                public void onOpen(ServerHandshake serverHandshake) {
                    Log.i("Websocket", "onOpen: " + serverHandshake.getHttpStatus() + " " + serverHandshake.getHttpStatusMessage());
                }

                @Override
                public void onMessage(String s) {
                    Log.i("Websocket", "onMessage: " + s);
                }

                @Override
                public void onClose(int i, String s, boolean b) {
                    Log.i("Websocket", "onClose: " + i + " " + s);
                }

                @Override
                public void onError(Exception e) {
                    Log.i("Websocket", "onError: " + e.getMessage());
                }
            };
            WebSocketClient.WebSocketClientFactory factory = new DefaultSSLWebSocketClientFactory(MyApplication.getSSLContext());
            mWebSocketClient.setWebSocketFactory(factory);
            mWebSocketClient.connect();
```
I hope it works for you.

**Comment by oakkitten** [comment]
@douglasjunior upgrade to java 7 and squash them catches tho

**Comment by douglasjunior** [comment]
On Server I'm using Java EE 7. My `Endpoint`.

```java
@ServerEndpoint("/test")
public class TestEndpoint {

    @OnOpen
    public void onOpen(Session s) {
        System.out.println("websocket.onOpen: " + s);
    }

    @OnClose
    public void onClose(CloseReason c) {
        System.out.println("websocket.onClose: " + c.toString());
    }

    @OnError
    public void onError(Throwable t) {
        System.out.println("websocket.onError: " + t.getMessage());
        t.printStackTrace();
    }

    @OnMessage
    public String onMessage(String message) {
        System.out.println("websocket.onMessage: " + message);
        return "Received on Server: " + message;
    }
}
```

**Comment by douglasjunior** [comment]
If using current devlopment version, change this:
```java
WebSocketClient.WebSocketClientFactory factory = new DefaultSSLWebSocketClientFactory(MyApplication.getSSLContext());
mWebSocketClient.setWebSocketFactory(factory);
mWebSocketClient.connect()
```
For this:
```java
mWebSocketClient.setSocket(HttpsURLConnection.getDefaultSSLSocketFactory().createSocket());
mWebSocketClient.connectBlocking();
```

**Comment by ukotdiya01** [comment]
Now there is no WebSocketClientFactory or setWebSocketFactory methods available  for WebsocketClient.  I am getting following error which is failure of TLS handshake. I am able to connect to this webserver using my iOS app on wss.

05-25 19:27:03.474 5920-18807/org.java_websocket.client D/TOOTALLNATE: Exception occurred ...
                                                                       javax.net.ssl.SSLException: Connection closed by peer
05-25 19:27:03.474 5920-18807/org.java_websocket.client W/System.err: javax.net.ssl.SSLException: Connection closed by peer
05-25 19:27:03.474 5920-18807/org.java_websocket.client W/System.err:     at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
05-25 19:27:03.474 5920-18807/org.java_websocket.client W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:378)
05-25 19:27:03.474 5920-18807/org.java_websocket.client W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.<init>(OpenSSLSocketImpl.java:649)
05-25 19:27:03.474 5920-18807/org.java_websocket.client W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:620)
05-25 19:27:03.484 5920-18807/org.java_websocket.client W/System.err:     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:167)
05-25 19:27:03.484 5920-18807/org.java_websocket.client W/System.err:     at java.lang.Thread.run(Thread.java:856)

**Comment by syedhabib53** [comment]
I am trying `wss` connection in Android using @douglasjunior mentioned, I am keep getting following error,

```
08-31 10:33:20.907 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x10 ret=1
08-31 10:33:20.907 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 handshake start in UNKWN  before/connect initialization
08-31 10:33:20.907 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback calling handshakeCompleted
08-31 10:33:20.907 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback completed
08-31 10:33:20.908 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1001 ret=1
08-31 10:33:20.908 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:UNKWN  before/connect initialization
08-31 10:33:20.908 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.908 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1001 ret=1
08-31 10:33:20.908 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:23WCHA SSLv2/v3 write client hello A
08-31 10:33:20.908 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.908 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
08-31 10:33:20.908 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:error exit in 23RSHA SSLv2/v3 read server hello A
08-31 10:33:20.908 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.938 15447-15484/com.qruize.vfstest D/IMGSRV: gralloc_register_buffer:1390: hnd=0x7f9f21f440 ID=44475 fd=77 ref=1
08-31 10:33:20.938 15447-15484/com.qruize.vfstest D/GraphicBuffer: register, handle(0x7f9f21f440) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1001 ret=1
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:3RSH_A SSLv3 read server hello A
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
08-31 10:33:20.941 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
08-31 10:33:20.942 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback ignored
08-31 10:33:20.942 15447-15552/com.qruize.vfstest D/NativeCrypto: ssl=0x7f93823280 info_callback where=0x1002 ret=-1
```

Please get me out of this. Thanks in advance.

**Comment by syedhabib53** [comment]
#Using [this](https://github.com/TooTallNate/Java-WebSocket/issues/293) above issue has fixed.
