### ISSUE TITLE
The Client crashes on Hybi10 while transformSingleFrame

### ISSUE THREAD

**Issue by prdatur** [TooTallNate/Java-WebSocket#150]
Hello,

I'm using the Client of your WebSocket. I connect to my Hybi10 WebSocket server without errors. The Server can successfully send the client messages but since i want to send from the java client a message to the server i get always:
org.java_websocket.exceptions.InvalidFrameException: bad rsv 4

**Comment by 9992800** [comment]
}
process(193): {HTTP/1.1 101 Switching Protocols
Server: openresty/1.9.7.1
Date: Fri, 08 Jan 2016 03:55:24 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: Fv+SNPWZc2Q42hHTESrhPYZy7Fk=

}
org.java_websocket.exceptions.InvalidFrameException: bad rsv 4
	at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:308)
	at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:285)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:321)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
	at java.lang.Thread.run(Thread.java:722)
write(212): {GET /online_test?system=-1&80010086=-1&80010087=-1&self=2 HTTP/1.1
Connection: Upgrade
Host: chat.jucaicun.com:443
Sec-WebSocket-Key: T3Z9W03umkn4iFadT3GlbQ==
Sec-WebSocket-Version: 13
Upgrade: websocket

}

**Comment by 43350860** [comment]
@9992800 Is this the problem solved?
```java
org.java_websocket.exceptions.InvalidFrameException: bad rsv 4
at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:308)
at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:285)
at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:321)
at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
at java.lang.Thread.run(Thread.java:722)
```

**Comment by 43350860** [comment]
@Davidiusdadi Hello, how is this problem solved?
```java
org.java_websocket.exceptions.InvalidFrameException: bad rsv 4
at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:308)
at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:285)
at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:321)
at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
at java.lang.Thread.run(Thread.java:722)
```

**Comment by marci4** [comment]
Hello @43350860,

Draft_10 is deprecated. Please use Draft_6455.

Greetings
marci4
