### ISSUE TITLE
Secure websocket closes after a few minutes

### ISSUE THREAD

**Issue by galdolber** [TooTallNate/Java-WebSocket#200]
I'm not doing anything special, just connecting and waiting and I get this:

close with code:  1006 
java.lang.NullPointerException
    at org.java_websocket.drafts.Draft_10.acceptHandshakeAsClient(Draft_10.java:71)
    at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:264)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:159)
    at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:239)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
    at posplugin.client.proxy$org.java_websocket.client.WebSocketClient$0.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:680)

**Comment by dragonlr** [comment]
Did you fix this bug? I run this socket standard alone
java.lang.NullPointerException
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:321)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:709)
2015-09-11 09:52:24,455 ERROR [MainSicbo] onError
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1186)
	at java.lang.Thread.join(Thread.java:1239)
	at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:229)
	at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:235)
	at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:464)
	at org.java_websocket.server.WebSocketServer.access$100(WebSocketServer.java:51)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:716)

**Comment by marci4** [comment]
Hello everyone,

is this with the latest version still an issue?

Since the codebase changed a lot, I cannot use stacktrace.

Greetings
marci4

**Comment by ikermart** [comment]
@marci4  I seems that still closes the server. I have a timer, that every 3 seconds sends data to websocket server from my android app.
I have an event that in certain moment stops sending data (semaphor), If i restarted sending data before 5 minutes, the server response ok, but if the stop is more than 5 minutes, I send the request but not onMessage is called neither onError.
Is there a internal timeout configuration?

**Comment by marci4** [comment]
Hello @ikermart,

no there is no internal timeout configuration right now!
With the upcoming release of 1.3.4 I will add a feature which automatically detects lost connections.
I will also change the implementation of your SSLSocketChannel which may also fix this!

Greetings
marci4

**Comment by marci4** [comment]
Any update?

**Comment by marci4** [comment]
No feedback for months!

Please open a separate issue if you still have any problem!
Greetings
marci4
