### ISSUE TITLE
Getting orphaned threads on linux

### ISSUE THREAD

**Issue by sdidrik** [TooTallNate/Java-WebSocket#203]
I have a java server running on linux that opens websockets with a local apache/python server. It is acting as a proxy for web browsers that do not handle websockets. I am getting the following errors though:
Full thread dump OpenJDK 64-Bit Server VM (23.7-b01 mixed mode):

"Thread-2" prio=10 tid=0x0000000000f1a000 nid=0xad6e runnable [0x00007fd0ac3ea000]
   java.lang.Thread.State: RUNNABLE
    at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
    at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:228)
    at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:81)
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
    - locked <0x00000000ebdf9d48> (a sun.nio.ch.Util$2)
    - locked <0x00000000ebdf9cc8> (a java.util.Collections$UnmodifiableSet)
    - locked <0x00000000ebdf9a40> (a sun.nio.ch.EPollSelectorImpl)
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
    at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:238)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:204)
    at java.lang.Thread.run(Thread.java:724)

"Abandoned connection cleanup thread" daemon prio=10 tid=0x0000000000e6c000 nid=0xad66 in Object.wait() [0x00007fd0ac6fc000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000eb7d02b8> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
    - locked <0x00000000eb7d02b8> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
    at com.mysql.jdbc.NonRegisteringDriver$1.run(NonRegisteringDriver.java:93)

"Timer-0" prio=10 tid=0x00007fd0b8172800 nid=0xad4b in Object.wait() [0x00007fd0ac8fe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000eb768598> (a java.util.TaskQueue)
    at java.util.TimerThread.mainLoop(Timer.java:552)
    - locked <0x00000000eb768598> (a java.util.TaskQueue)
    at java.util.TimerThread.run(Timer.java:505)

"Service Thread" daemon prio=10 tid=0x00007fd0b8120800 nid=0xad49 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=10 tid=0x00007fd0b811e000 nid=0xad48 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=10 tid=0x00007fd0b811b000 nid=0xad47 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Command Reader" daemon prio=10 tid=0x00007fd094001000 nid=0xad44 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Event Helper Thread" daemon prio=10 tid=0x00007fd0b8119000 nid=0xad41 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Transport Listener: dt_socket" daemon prio=10 tid=0x00007fd0b8115000 nid=0xad40 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=10 tid=0x00007fd0b8107800 nid=0xad3d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=10 tid=0x00007fd0b80af800 nid=0xad3c in Object.wait() [0x00007fd0ad881000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000eb6b5728> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
    - locked <0x00000000eb6b5728> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
    at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:189)

"Reference Handler" daemon prio=10 tid=0x00007fd0b80ad000 nid=0xad3b in Object.wait() [0x00007fd0ad982000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000eb6b52b0> (a java.lang.ref.Reference$Lock)
    at java.lang.Object.wait(Object.java:503)
    at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
    - locked <0x00000000eb6b52b0> (a java.lang.ref.Reference$Lock)

"main" prio=10 tid=0x00007fd0b800a800 nid=0xad37 runnable [0x00007fd0bfbb7000]
   java.lang.Thread.State: RUNNABLE
    at java.net.PlainSocketImpl.socketAccept(Native Method)
    at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
    at java.net.ServerSocket.implAccept(ServerSocket.java:530)
    at java.net.ServerSocket.accept(ServerSocket.java:498)
    at pollingdaemon.baseline.com.PollingDaemon.main(PollingDaemon.java:222)

"VM Thread" prio=10 tid=0x00007fd0b80a4800 nid=0xad3a runnable 

"GC task thread#0 (ParallelGC)" prio=10 tid=0x00007fd0b8018000 nid=0xad38 runnable 

"GC task thread#1 (ParallelGC)" prio=10 tid=0x00007fd0b801a000 nid=0xad39 runnable 

"VM Periodic Task Thread" prio=10 tid=0x00007fd0b812b000 nid=0xad4a waiting on condition 

JNI global references: 1318

Heap
 PSYoungGen      total 18432K, used 8795K [0x00000000eb6b0000, 0x00000000ecb40000, 0x0000000100000000)
  eden space 15808K, 55% used [0x00000000eb6b0000,0x00000000ebf46d50,0x00000000ec620000)
  from space 2624K, 0% used [0x00000000ec8b0000,0x00000000ec8b0000,0x00000000ecb40000)
  to   space 2624K, 0% used [0x00000000ec620000,0x00000000ec620000,0x00000000ec8b0000)
 ParOldGen       total 42176K, used 0K [0x00000000c2400000, 0x00000000c4d30000, 0x00000000eb6b0000)
  object space 42176K, 0% used [0x00000000c2400000,0x00000000c2400000,0x00000000c4d30000)
 PSPermGen       total 21248K, used 7580K [0x00000000b7e00000, 0x00000000b92c0000, 0x00000000c2400000)
  object space 21248K, 35% used [0x00000000b7e00000,0x00000000b85673d8,0x00000000b92c0000)

We are seeing a lot of threads in a wait_close state that do not go away and think the above has some thing to do with it.

**Comment by marci4** [comment]
Closing issue.

Greetings
marci4
