### ISSUE TITLE
NullPointerException in SocketChannelIOHelper.batch

### ISSUE THREAD

**Issue by sippykup** [TooTallNate/Java-WebSocket#210]
I just upgraded from our fork of 1.3.0 to the latest code from head, and encountered the following error as soon as I attempted a connection to the server, which immediately caused the server to stop.

2013-09-27 09:22:40,026 ERROR (WebsocketSelector123174) Websocket connection error from null
java.lang.NullPointerException
  at org.java_websocket.SocketChannelIOHelper.batch(SocketChannelIOHelper.java:64)
  at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:352)

**Comment by MrSam** [comment]
Hmm, someone looking into this ? 

I was quite happy with my java_websocket server implementation :/

**Comment by marci4** [comment]
Is there any update on this issue?

Greetings
marci4

**Comment by marci4** [comment]
No feedback!

If you still have this issue, please open a separate thread!
Greetings
marci4
