### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: ChatServer can only be started once.

### ISSUE THREAD

**Issue by ghost** [TooTallNate/Java-WebSocket#227]
Love this lib!

One issue with the "restart" command for ChatServer.java, if I type "restart", I get this error:

Exception in thread "main" java.lang.IllegalStateException: ChatServer can only be started once.
    at org.java_websocket.server.WebSocketServer.start(WebSocketServer.java:186)
    at ChatServer.main(ChatServer.java:69)

**Comment by feixiangsmile** [comment]
Do you solve this problem? I am also find this problem, can you help me?

**Comment by marci4** [comment]
Hello @feixiangsmile,

this is an error in the example.
Right now it is not possible to reuse a server.

Greetings
marci4
