### ISSUE TITLE
Deadlock if a client closes a connection while server is stopping

### ISSUE THREAD

**Issue by gzm0** [TooTallNate/Java-WebSocket#287]
On version 1.2.0:

Thread that stops the server:

```
java.lang.Thread.State: BLOCKED (on object monitor)
    at org.java_websocket.WebSocketImpl.flushAndClose(WebSocketImpl.java:487)
    - waiting to lock <0x0000000159e1c158> (a org.java_websocket.WebSocketImpl)
    at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:413)
    at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:526)
    at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:207)
    - locked <0x0000000158f86228> (a java.util.HashSet)
    at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:232)
    at ... <my code>
```

WebsocketSelector

```
java.lang.Thread.State: BLOCKED (on object monitor)
    at org.java_websocket.server.WebSocketServer.removeConnection(WebSocketServer.java:509)
    - waiting to lock <0x0000000158f86228> (a java.util.HashSet)
    at org.java_websocket.server.WebSocketServer.onWebsocketClose(WebSocketServer.java:488)
    at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:459)
    - locked <0x0000000159e1c158> (a org.java_websocket.WebSocketImpl)
    at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:472)
    at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:516)
    at org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:16)
    at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:327)
    at java.lang.Thread.run(Thread.java:724)
```

The problem is that `WebSocketImpl` [locks on itself](https://github.com/TooTallNate/Java-WebSocket/blob/v1.2.0/src/main/java/org/java_websocket/WebSocketImpl.java#L426) and then on `connections` inside `WebSocketServer` via [`onWebsocketClose`](https://github.com/TooTallNate/Java-WebSocket/blob/v1.2.0/src/main/java/org/java_websocket/WebSocketImpl.java#L441).

The `WebSocketServer` on the other hand first [locks on `connections`](https://github.com/TooTallNate/Java-WebSocket/blob/v1.2.0/src/main/java/org/java_websocket/server/WebSocketServer.java#L206) and then on the said `WebSocketImpl` via [`close`](https://github.com/TooTallNate/Java-WebSocket/blob/v1.2.0/src/main/java/org/java_websocket/server/WebSocketServer.java#L208).

**Comment by metabrain** [comment]
+1

Also came across this issue. Though it only happens on our TeamCity project.

```
Found one Java-level deadlock:
=============================
"WebsocketSelector18":
  waiting to lock monitor 0x0000000028ef87c8 (object 0x00000005c00e1190, a java.util.HashSet),
  which is held by "main"
"main":
  waiting to lock monitor 0x00000000018b3d48 (object 0x000000071d80b900, a org.java_websocket.WebSocketImpl),
  which is held by "WebsocketSelector18"

Java stack information for the threads listed above:
===================================================
"WebsocketSelector18":
	at org.java_websocket.server.WebSocketServer.removeConnection(WebSocketServer.java:508)
	- waiting to lock <0x00000005c00e1190> (a java.util.HashSet)
	at org.java_websocket.server.WebSocketServer.onWebsocketClose(WebSocketServer.java:488)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:459)
	- locked <0x000000071d80b900> (a org.java_websocket.WebSocketImpl)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:479)
	at org.java_websocket.SocketChannelIOHelper.batch(SocketChannelIOHelper.java:64)
	- locked <0x000000071d80b900> (a org.java_websocket.WebSocketImpl)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:349)
	at java.lang.Thread.run(Thread.java:745)
"main":
	at org.java_websocket.WebSocketImpl.flushAndClose(WebSocketImpl.java)
	- waiting to lock <0x000000071d80b900> (a org.java_websocket.WebSocketImpl)
	at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:413)
	at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:526)
	at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:207)
	- locked <0x00000005c00e1190> (a java.util.HashSet)
	at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:232)
	at our.internal.classes.OurWebSocket.stop(OurWebSocket.java:59)
	at ...<junit internal test harnesses>

Found 1 deadlock.
```

**Comment by stefanjauker** [comment]
+1

```
18:48:46      [java] java.lang.Exception: test timed out after 60000 milliseconds
18:48:46      [java] 	at org.java_websocket.WebSocketImpl.flushAndClose(WebSocketImpl.java:487)
18:48:46      [java] 	at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:413)
18:48:46      [java] 	at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:526)
18:48:46      [java] 	at org.java_websocket.client.WebSocketClient.close(WebSocketClient.java:155)
18:48:46      [java] 	at io.socket.WebsocketTransport.disconnect(WebsocketTransport.java:44)
18:48:46      [java] 	at io.socket.IOConnection.cleanup(IOConnection.java:434)
18:48:46      [java] 	at io.socket.IOConnection.unregister(IOConnection.java:289)
18:48:46      [java] 	at io.socket.SocketIO.disconnect(SocketIO.java:323)
```

**Comment by marci4** [comment]
This issue should be fixed with the latest version.

Greetings
marci4
