### ISSUE TITLE
SSL Websockets give rejectedExecution exception

### ISSUE THREAD

**Issue by mirraj2** [TooTallNate/Java-WebSocket#315]
Wish I could use this library, but it doesn't seem to work with SSL :(

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@270014db rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7dbd8f68[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
FINALLY
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
    at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
    at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
    at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
    at org.java_websocket.SSLSocketChannel2.consumeDelegatedTasks(SSLSocketChannel2.java:175)
    at org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:140)
    at org.java_websocket.SSLSocketChannel2.<init>(SSLSocketChannel2.java:82)
    at org.java_websocket.server.DefaultSSLWebSocketServerFactory.wrapChannel(DefaultSSLWebSocketServerFactory.java:39)
    at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:321)
    at java.lang.Thread.run(Thread.java:745)

**Comment by jacklink01** [comment]
Bump. Having the same problem. :(

**Comment by duke-robby** [comment]
Strange issue, only happens when an SSL client is disconnecting.

**Comment by bendem** [comment]
[This](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/SSLSocketChannel2.java#L311) closes the ThreadPool shared between all the SSLSocketChannel2s, preventing any further call to processHandshake in another one.

**Comment by bendem** [comment]
Partially fixed by #216, just need to call the new shutdown method.

**Comment by BrushfireDigitalServices** [comment]
Now #331 incorporates #216 and calls the new shutdown method. Will close this after #331 is merged.

**Comment by BrushfireDigitalServices** [comment]
Related: #270

**Comment by PerwinCZ** [comment]
Fixed by #375 aswell

**Comment by bendem** [comment]
@marci4 this is fixed.

**Comment by marci4** [comment]
@bendem thx for the response. Closing it
