### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by hanmo9** [TooTallNate/Java-WebSocket#414]
i use websocket as server, browser as client,sometimes has the exception 
this is the detail:
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:12)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:327)
        at java.lang.Thread.run(Thread.java:745)
why this error? please give me some advice

**Comment by marci4** [comment]
Hello @hanmo9,

please read up on the short explanation for "Connection reset by peer" [here](http://stackoverflow.com/a/1434506).

Greetings
marci4
