### ISSUE TITLE
the remote Endpoint was in state [Text_FULL_WRITING] 

### ISSUE THREAD

**Issue by brucelwl** [TooTallNate/Java-WebSocket#421]
When I quickly click the Android UI button will appear when the following error, what is a good way to solve it

信息: java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method
java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1177)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.textStart(WsRemoteEndpointImplBase.java:1140)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendStringByCompletion(WsRemoteEndpointImplBase.java:213)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendStringByFuture(WsRemoteEndpointImplBase.java:201)
	at org.apache.tomcat.websocket.WsRemoteEndpointAsync.sendText(WsRemoteEndpointAsync.java:53)
	at com.lwl.android.WsServer.sendToMana(WsServer.java:50)
	at com.lwl.android.WsServer.onMessage(WsServer.java:35)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:80)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:399)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:500)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:295)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:71)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:185)
	at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:198)
	at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:96)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:647)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

-------------------------------------------------------------------------------------------------------------
following is my code
package com.ws.activity;

import java.net.URI;
import java.net.URISyntaxException;
import java.nio.ByteBuffer;

import org.java_websocket.WebSocket;
import org.java_websocket.drafts.Draft_17;
import org.java_websocket.exceptions.InvalidDataException;
import org.java_websocket.framing.Framedata.Opcode;
import org.java_websocket.framing.FramedataImpl1;

import android.app.Activity;
import android.os.Bundle;
import android.os.Handler;
import android.os.Message;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import com.ws.client.WsClient;

public class MainActivity extends Activity {
	WsClient client = null;
	Button button1;
	Button button2;
	EditText editText;
	private TextView textView1;
	
	public static Handler handler;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		button1 = (Button) this.findViewById(R.id.button1);
		button2 = (Button) this.findViewById(R.id.button2);
		editText = (EditText) this.findViewById(R.id.editText);
		textView1 = (TextView) this.findViewById(R.id.textView1);
		
		OnClick onClick = new OnClick();
		button1.setOnClickListener(onClick);
		button2.setOnClickListener(onClick);
		
		handler = new Handler(){
			@Override
			public void handleMessage(Message msg) {
				textView1.setText(msg.obj.toString());
			}
		};

		try {
			//String path = "ws://10.0.2.2:8081/WebSocketAndroid/android/ws";
			String path = "ws://192.168.43.177:8081/WebSocketAndroid/android/ws";
			client = new WsClient(this,new URI(path), new Draft_17());
			client.connect();
		} catch (URISyntaxException e) {
			e.printStackTrace();
		}
	}

	class OnClick implements OnClickListener {
		@Override
		public void onClick(View v) {
			switch (v.getId()) {
			case R.id.button1: // "发送"
				synchronized(client){
					client.send(editText.getText().toString()+"哈哈哈哈 "+client.hasBufferedData());
				}
				break;

			case R.id.button2: // "心跳"
				ByteBuffer longelinebuffer = ByteBuffer.wrap( "liwenlong".getBytes() );
				longelinebuffer.rewind();
				WebSocket connection = client.getConnection();
				if (connection != null && connection.isOpen()) {
					FramedataImpl1 framedataImpl1 = new FramedataImpl1(Opcode.PING);
					try {
						ByteBuffer wrap = ByteBuffer.wrap("liwenlong".getBytes());
						wrap.rewind();
						framedataImpl1.setPayload(wrap);
						framedataImpl1.setTransferemasked(true);
						framedataImpl1.setFin(true);
					} catch (InvalidDataException e) {
						e.printStackTrace();
					}
					connection.sendFrame(framedataImpl1);
					
					Log.d("Tag", "if PING");
				}
				Log.d("Tag", "PING");
				break;

			default:
				break;
			}

		}

	}

}
-----------------------------------------------------------------------------------------------------------------
package com.ws.client;

import java.net.URI;

import org.java_websocket.WebSocket;
import org.java_websocket.client.WebSocketClient;
import org.java_websocket.drafts.Draft;
import org.java_websocket.framing.Framedata;
import org.java_websocket.handshake.ServerHandshake;

import android.os.Message;
import android.util.Log;

import com.ws.activity.MainActivity;

public class WsClient extends WebSocketClient{

	MainActivity activity = null;
	
	public WsClient(URI serverUri) {
		super(serverUri);
	}
	
	public WsClient(URI serverUri, Draft draft) {
		super(serverUri, draft);
	}
	
	public WsClient(MainActivity activity,URI serverUri, Draft draft) {
		super(serverUri, draft);
		this.activity  = activity;
	}
	
	@Override
	public void onOpen(ServerHandshake shake) {
		Log.d("Tag", "shake getHttpStatus "+shake.getHttpStatus());
		
		Message obtainMessage = MainActivity.handler.obtainMessage(1, "shake getHttpStatus "+shake.getHttpStatus());
		MainActivity.handler.sendMessage(obtainMessage);
		
	}
	
	@Override
	public void onMessage(String msg) {
		Log.d("Tag", "onMessage "+msg);
		
		Message obtainMessage = MainActivity.handler.obtainMessage(1, "onMessage "+msg+" "+System.currentTimeMillis());
		MainActivity.handler.sendMessage(obtainMessage);
		
	}

	@Override
	public void onClose(int arg0, String arg1, boolean arg2) {
		
		Log.d("Tag", "onClose "+arg0+" "+arg1+" "+arg2);
		
		Message obtainMessage = MainActivity.handler.obtainMessage(1, "onClose 断开连接");
		MainActivity.handler.sendMessage(obtainMessage);
	}

	@Override
	public void onError(Exception arg0) {
		try {
			throw arg0;
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	

	@Override
	public void onWebsocketPing(WebSocket conn, Framedata framedata) {
		Log.d("Tag","onWebsocketPing ... "+ framedata.toString());
	}

	@Override
	public void onWebsocketPong(WebSocket conn, Framedata framedata) {
		Log.d("Tag", "onWebsocketPong..."+"received fragment: " + new String( framedata.getPayloadData().array() ));
		
	
	}

	

	
	
}

**Comment by marci4** [comment]
hey @brucelwl,

am I reading the stacktrace wrong or do you use the tomcat implementation and not the implementation provided by this project?

Greetings
marci4

**Comment by marci4** [comment]
No response.
Stacktrace looks like tomcat.

Closing issue...
Greetings
marci4
