### ISSUE TITLE
Websocket Server behaviour with SSLException

### ISSUE THREAD

**Issue by GeminiLoal** [TooTallNate/Java-WebSocket#433]
Hi, I think there is a problem on how the SSLException is handle. 

In my case, I am able to create the secure server, let's say at wss://123.123.1.1:8887, but if i try to connect with a plain client to ws:// 
I obtain: 

javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
Connection closed because ofjavax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?	at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.java_websocket.SSLSocketChannel2.unwrap(SSLSocketChannel2.java:167)
	at org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:135)
	at org.java_websocket.SSLSocketChannel2.<init>(SSLSocketChannel2.java:83)
	at org.java_websocket.server.DefaultSSLWebSocketServerFactory.wrapChannel(DefaultSSLWebSocketServerFactory.java:39)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:314)
	at java.lang.Thread.run(Thread.java:745)

(the stack trace is visible because I added the ex.printStackTrac() to the catch)
The handler is here: https://github.com/TooTallNate/Java-WebSocket/blob/32359966fb5ad917c25bd00c73b9baeb6be17472/src/main/java/org/java_websocket/server/WebSocketServer.java#L454 

After this exeption, the server is no longer reachable, not even from a secure client. 

A similar behavior appears if I  check the port with nmap, the stack trace in this case is: 

java.io.IOException: Connessione interrotta dal corrispondente
Connection closed because ofjava.io.IOException: Connessione interrotta dal corrispondente
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:128)
	at org.java_websocket.SSLSocketChannel2.<init>(SSLSocketChannel2.java:83)
	at org.java_websocket.server.DefaultSSLWebSocketServerFactory.wrapChannel(DefaultSSLWebSocketServerFactory.java:39)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:314)
	at java.lang.Thread.run(Thread.java:745)

Te port results open at the first run of the command, but if I try a second time it appears closed and no longer reachable. 

if I disable security, everything works fine.

Greetings
L

**Comment by marci4** [comment]
Should be fixed with the commit

Greetings
marci4
