### ISSUE TITLE
InvalidFrameException

### ISSUE THREAD

**Issue by dan335** [TooTallNate/Java-WebSocket#495]
I just got this error.  Not sure what triggered it.  Do I need to catch InvalidFrameException somewhere or is this a bug?

````
2017-05-31T04:25:12.231377063Z Websocket Server Error
2017-05-31T04:25:12.236709586Z org.java_websocket.exceptions.InvalidFrameException: bad rsv 4
2017-05-31T04:25:12.237717717Z 	at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:297)
2017-05-31T04:25:12.237912056Z 	at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:273)
2017-05-31T04:25:12.238860170Z 	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:318)
2017-05-31T04:25:12.239233028Z 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:154)
2017-05-31T04:25:12.239965117Z 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:817)
2017-05-31T15:39:52.674487985Z Error while reading from remote connection: java.lang.NullPointerException
2017-05-31T15:39:52.674922341Z java.lang.NullPointerException
2017-05-31T15:39:52.675290202Z 	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:318)
2017-05-31T15:39:52.675402038Z 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:154)
2017-05-31T15:39:52.675419791Z 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:817)
2017-05-31T16:00:04.467273880Z Websocket Server Error
2017-05-31T16:00:04.468512653Z org.java_websocket.exceptions.InvalidFrameException: bad rsv 4
2017-05-31T16:00:04.468544713Z 	at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:297)
2017-05-31T16:00:04.468561585Z 	at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:273)
2017-05-31T16:00:04.468569730Z 	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:318)
2017-05-31T16:00:04.468577116Z 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:154)
2017-05-31T16:00:04.468597173Z 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:817)
2017-05-31T16:02:31.850651228Z Error while reading from remote connection: java.lang.NullPointerException
2017-05-31T16:02:31.851561390Z java.lang.NullPointerException
2017-05-31T16:02:31.851698429Z 	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:318)
2017-05-31T16:02:31.851854396Z 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:154)
2017-05-31T16:02:31.852191799Z 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:817)
2017-05-31T16:07:01.096716640Z Websocket Server Error
2017-05-31T16:07:01.100530800Z org.java_websocket.exceptions.InvalidFrameException: bad rsv 4
2017-05-31T16:07:01.100654778Z 	at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:297)
2017-05-31T16:07:01.100665098Z 	at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:273)
2017-05-31T16:07:01.100719106Z 	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:318)
2017-05-31T16:07:01.100725340Z 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:154)
2017-05-31T16:07:01.100736021Z 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:817)
2017-05-31T16:35:07.882924957Z Websocket Server Error
2017-05-31T16:35:07.883557540Z org.java_websocket.exceptions.InvalidFrameException: bad rsv 4
2017-05-31T16:35:07.884203612Z 	at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:297)
2017-05-31T16:35:07.890608658Z 	at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:273)
2017-05-31T16:35:07.890674873Z 	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:318)
2017-05-31T16:35:07.890716351Z 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:154)
2017-05-31T16:35:07.892747124Z 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:817)
````

**Comment by marci4** [comment]
Hello @dan335,

could you tell me what version you are using? Is it the 1.3.3 ?
What are you using as a client?

To the exception itself:
This is an indication that the recieved frame is containing an invalid bit.
Right now this lib is supporting no exception so the rsv should always be 0.
So this is a valid exception and should not be caught (it should not happen with a valid endpoint).

Greetings
marci4

**Comment by dan335** [comment]
Version 1.3.3.  It's from a game.  I'm using plain javascript websockets but some players try to cheat or create bots by sending messages themselves.  I'm guessing it's caused by one of the players but have no way of knowing.

Is there a place I can catch that exception so that it doesn't crash if this happens again?

**Comment by marci4** [comment]
Hello @dan335,

this exception should just disconnect the specific user and not crash the server itself!

The problem is that according to the spec the server has to dc the client.
` If a nonzero value is received and none of the negotiated extensions defines the meaning of such a nonzero value, the receiving endpoint MUST _Fail the WebSocket Connection_.` (https://tools.ietf.org/html/rfc6455#section-5.2)

Greetings
marci4

**Comment by dan335** [comment]
I saw this error again and the server was still up so they must be unrelated.  Thanks, closing.
