### ISSUE TITLE
[Java Web Start] -  java.io.IOException: The handle is invalid

### ISSUE THREAD

**Issue by Dayssam** [TooTallNate/Java-WebSocket#519]
Hi,

Thank your four your efforts...

I got the error bellow when i used this code in my webstart but in Eclipse i dont get error

`
			
			
			WSServer s = new WSServer( port );
			s.start();
			
			System.out.println( "WSServer started on port: " + s.getPort() );
			
			
			BufferedReader sysin = new BufferedReader( new InputStreamReader( System.in ) );
			
	
			while ( true ) {
				
				try {
					String in = sysin.readLine();
					s.sendToAll( in );
					if( in.equals( "exit" ) ) {
						s.stop();
						System.out.println("STOP");
						break;
					}
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}`

& I got a continious error in this line 
`String in = sysin.readLine();`

The error :

`Java Web Start 11.111.2.14 x86
Utilisation de la version JRE 1.8.0_111-b14 Java HotSpot(TM) Client VM
Répertoire de base de l'utilisateur = C:\Users\zakaria
----------------------------------------------------
c:   effacer la fenêtre de la console
f:   finaliser les objets de la file d'attente de finalisation
g:   nettoyer la mémoire
h:   afficher ce message d'aide
m:   imprimer le relevé d'utilisation de la mémoire
o:   déclencher la journalisation
p:   recharger la configuration du proxy
q:   masquer la console
r:   recharger la configuration des règles
s:   vider les propriétés système et de déploiement
t:   vider la liste des threads
v:   vider la pile des threads
0-5: fixer le niveau de trace à <n>
----------------------------------------------------
Missing Application-Name manifest attribute for: http://192.168.1.31:8094/MyApp/resources/jws/jws.jar
Missing Permissions manifest attribute in main jar: http://192.168.1.31:8094/MyApp/resources/jws/jws.jar
WSServer started on port: 6789
Finished DialogBox
java.io.IOException: Descripteur non valide
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at mypackage.MyClass.main(SofiSignaJWS.java:399)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.io.IOException: Descripteur non valide
...etc

**Comment by marci4** [comment]
Hello @Dayssam,

yeah that looks like there is no input device on the server (what you expect!)
Just remove these lines!
```java
		BufferedReader sysin = new BufferedReader( new InputStreamReader( System.in ) );
		while ( true ) {
			
			try {
				String in = sysin.readLine();
				s.sendToAll( in );
				if( in.equals( "exit" ) ) {
					s.stop();
					System.out.println("STOP");
					break;
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
```

Greetings
marci4

**Comment by Dayssam** [comment]
Thank you @marci4 , it works like a charm

But the question is , what the code above did ?

and if i want the service dont stop like 
```
while(true){
}
```

How can i be sure the app doesn't stop ?

**Comment by marci4** [comment]
Hello @Dayssam 

the code allows you to write messages into the console which the server then sends.
This may be handy if you want to send something out of your IDE. 

The server won't stop because it is running in a seperat thread!

Greetings
marci4

**Comment by Dayssam** [comment]
Thank you very much @marci4 for your time. :100:
