### ISSUE TITLE
java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by lifubang** [TooTallNate/Java-WebSocket#545]
I use 1.3.4
But in server's log, there so many errors as follows:
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
	at org.java_websocket.SSLSocketChannel2.close(SSLSocketChannel2.java:320)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:513)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:543)
	at org.java_websocket.server.WebSocketServer.handleIOException(WebSocketServer.java:494)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:424)
	at java.lang.Thread.run(Thread.java:745)

How to deal with it?

**Comment by lifubang** [comment]
My server has 4 cpus. The cpu usage can be up to 25.94%, but there are only 100 connections.
How to know which method uses the most of cpu?

**Comment by marci4** [comment]
Hello @lifubang,

looks like the connection got lost due to some reason.
I should catch this exception!

Greetings
marci4

**Comment by marci4** [comment]
Catching this exception and give some additional info during active debug mode.

Closing issue!
Greetings
marci4
