### ISSUE TITLE
Client and server leave some threads running after close()

### ISSUE THREAD

**Issue by pcdv** [TooTallNate/Java-WebSocket#580]
I've been wanting to submit (or fix) this one for a long time.

My test runs the following code several times in a row
```
		WebSocketServer ws = new DummyWebSocketServer( port );

		ws.start();
		Thread.sleep( 100 );

		DummyWebSocket clt = new DummyWebSocket( port );
		clt.send( "foo" );
		Thread.sleep( 100 );
		clt.close();
		ws.stop();
``` 

then checks that after a while, no new threads are still alive.

## Expected Behavior

When both the server and the client are closed, all created threads should die (at least after a given delay).

## Current Behavior

Most of the time, some threads are still running after the test. Here is the output of the junit I wrote:

```

Thread-24
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.net.SocketInputStream.read(SocketInputStream.java:127)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:277)
    at java.lang.Thread.run(Thread.java:748)

WebsocketWriteThread
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at org.java_websocket.client.WebSocketClient$WebsocketWriteThread.run(WebSocketClient.java:463)
    at java.lang.Thread.run(Thread.java:748)

Timer-5
    at java.lang.Object.wait(Native Method)
    at java.util.TimerThread.mainLoop(Timer.java:552)
    at java.util.TimerThread.run(Timer.java:505)

java.lang.AssertionError: Found 3 zombie thread(s) 

	at org.junit.Assert.fail(Assert.java:88)
	at org.java_websocket.util.ThreadCheck.checkZombies(ThreadCheck.java:44)
```

## Possible Solution

I haven't looked in the code for a while but probably some cleanup is needed regarding 
stop conditions for both client and server. I will try to find some time and look into the 
issue if no one is interested.

## Steps to Reproduce (for bugs)

See above. I can submit my test if needed.

## Debug log (for bugs)
```
Connection lost timer started
write(154): {GET / HTTP/1.1
Connection: Upgrade
Host: localhost:58319
Sec-WebSocket-Key: u+COwPc+gIlMjkyWhCnAgw==
Sec-WebSocket-Version: 13
Upgrade: websocket

}
process(154): {GET / HTTP/1.1
Connection: Upgrade
Host: localhost:58319
Sec-WebSocket-Key: u+COwPc+gIlMjkyWhCnAgw==
Sec-WebSocket-Version: 13
Upgrade: websocket

}
write(212): {HTTP/1.1 101 Web Socket Protocol Handshake
Connection: Upgrade
Date: Sat, 21 Oct 2017 15:44:42 GMT
Sec-WebSocket-Accept: XS0GMBzGIPxJXuFs680DlBjLYvQ=
Server: TooTallNate Java-WebSocket
Upgrade: websocket

}
open using draft: Draft_6455 extension: DefaultExtension
process(212): {HTTP/1.1 101 Web Socket Protocol Handshake
Connection: Upgrade
Date: Sat, 21 Oct 2017 15:44:42 GMT
Sec-WebSocket-Accept: XS0GMBzGIPxJXuFs680DlBjLYvQ=
Server: TooTallNate Java-WebSocket
Upgrade: websocket

}
open using draft: Draft_6455 extension: DefaultExtension
Connection lost timer started
send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:3], payload:foo}
afterEnconding(3): {foo}
write(9): {����-.��B}
process(9): {����-.��B}
afterDecoding(3): {foo}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:3], payload:foo}
send frame: Framedata{ optcode:CLOSING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:2], payload:�}code: 1000
afterEnconding(2): {�}
write(8): {���k$�ك}
send frame: Framedata{ optcode:CLOSING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:2], payload:�}code: 1001
afterEnconding(2): {�}
write(4): {��}
Connection lost timer stopped
process(8): {���k$�ك}
```

## Context

This issue is mainly important because I run a lot of tests that involve starting a WS server and eventually closing it. The bug generates the creation of a log of zombie threads in big test suites.

## Your Environment

Tested on linux and macos with Java 8.

**Comment by pcdv** [comment]
After more investigation, the bug seems to be on client side. I gave more explicit names to created threads:
```

DummyClient
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.net.SocketInputStream.read(SocketInputStream.java:127)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:278)
    at java.lang.Thread.run(Thread.java:748)

DummyClient.WebsocketWriteThread
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at org.java_websocket.client.WebSocketClient$WebsocketWriteThread.run(WebSocketClient.java:464)
    at java.lang.Thread.run(Thread.java:748)

DummyClient.connectionLostTimer
    at java.lang.Object.wait(Native Method)
    at java.util.TimerThread.mainLoop(Timer.java:552)
    at java.util.TimerThread.run(Timer.java:505)
```

So visibly, the client is indefinitely trying to read on its socket which has not been closed by the server. If the socket was closed, the 3 threads would probably terminate as part of the cleanup. Looks like this happens when the server is killed too soon after the client sent its close request. Confirmed by adding sleep(500) before calling stop().

Adding a sleep() in my code is not an option because multiplied by the number of tests, it would make the test suite much longer.

There are 2 possible fixes:
 - client: force closing socket when close() is called (after a given delay)
 - server: force closing all client sockets when stop() is called

I'd rather go for the second solution, optionally adding a new method if the change of behavior is problematic.

Any issues with that?

Thanks

**Comment by marci4** [comment]
Hello @pcdv,

thank you very much for your bug report and the time you invested into it!

I will look into this tonight :)

Greetings
marci4

**Comment by pcdv** [comment]
Hi Marcel,

I pushed all the changes on my fork (the test + naming threads more explicitly). I can submit a PR if you like (the test suite is green when closeConnection() is called).

FYI the behavior is indeterministic when I remove the close()/closeConnection() call: sometimes the client is disconnected, sometimes not.

Thanks

**Comment by marci4** [comment]
Hello @pcdv,

I will take a look on your fork as well and come back to you!
Still I feel that the test suite should be green with close() as well. 

Apart from this, of course test suites are always very welcome :)

Timing issues are the best issues.... not ;)

Thank you!

Greetings
marci4

**Comment by marci4** [comment]
Hello @pcdv,

sorry for getting back to you just today!

Well there are a few things to consider
- the websocket protocol requires a close frame to be received to close a connection.  (see [here](https://tools.ietf.org/html/rfc6455#section-1.4))
-what you are testing is working, just not instant. But to the the required response by the other endpoint that is not possible!

Could you please elaborate why you require an instant close/cleanup?

Greetings
marci4

**Comment by pcdv** [comment]
Hi @marci4,

The context is a suite of automated tests simulating client and server processes that communicate together and are then killed. I need instant close because it makes the suite faster (with several hundred tests it can have a non negligible impact).

The instant cleanup is required because my tests are configured to fail if they leave some dangling threads behind. In my fork, this is enforced by:

```java
@Rule public ThreadCheck zombies = new ThreadCheck();
```

When I submitted the issue I had missed the closeConnection() method. I now have a working solution so I don't mind if you close the issue :)

Cheers

**Comment by marci4** [comment]
Hello @pcdv,

if you just require a client-server communication without a proper handshake close, then `closeConnection()` is just fine!

Closing this issue as solved!
Greetings
marci4
