### ISSUE TITLE
org.java_websocket.exceptions.WebsocketNotConnectedException

### ISSUE THREAD

**Issue by dlluotian** [TooTallNate/Java-WebSocket#601]
org.java_websocket.exceptions.WebsocketNotConnectedException
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:606)
	at org.java_websocket.WebSocketImpl.sendFrame(WebSocketImpl.java:632)
	at org.java_websocket.WebSocketImpl.sendPing(WebSocketImpl.java:639)
	at org.java_websocket.AbstractWebSocket$1.run(AbstractWebSocket.java:132)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

hi,My English is not good.
this is my bug information,Somebody can help me？

**Comment by marci4** [comment]
Probably duplicate of #579
