### ISSUE TITLE
Websocket connection gives timeout exception while running on a remote host

### ISSUE THREAD

**Issue by venkateshthallam** [TooTallNate/Java-WebSocket#634]
I have been able to successfully connect to an external WebSocket server and get the data. Moved the same code to Digital Ocean and the WebSocket connection fails with a timeout. I added logs and it fails when it sends a message and waits for the response.

Was wondering if there's an issue with the IP address and if I have to mention the IP and port specifically somewhere in the code or config.

Appreciate any help.

## Expected Behavior

Gets messages from the Websocket server.

## Current Behavior

Gets a socket timeout exception.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug log (for bugs)

2017-Dec-12 03:34:53.485 ERROR [main] o.s.b.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webSocketCron': Invocation of init method failed; nested exception is java.util.concurrent.RejectedExecutionException: Task org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WriteTask@23aae55 rejected from java.util.concurrent.ThreadPoolExecutor@5f574cc2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)

## Context

The WebSocket connection suddenly sometimes gets closed. I see there are some stale tcp connections to when I check with "netstat atn", like multiple tcp connections open with the same ip:port.

Was wondering when I kill my Java Process, would the tcp connection not get closed? If not, how to exit safely?

## Your Environment

* Version used: 1.3.6, tried with 1.3.7 too, but no luck.
* Java version: 1.8
* Operating System and version: Ubuntu 16.04.2 x64
* Endpoint Name and version: 
* Link to your project:

**Comment by marci4** [comment]
Hello @venkateshthallam,

right now I am not sure who I can help you anyway.

You should provide:
- the stack trace for this exception and the exception itself
- your enviroment (lib version, java version, operation system and version etc etc)
- your constructor call or some steps to repeat
- the debug log using `WebSocketImpl.Debug = true;`

Greetings
marci4

**Comment by marci4** [comment]
Any update ?

**Comment by venkateshthallam** [comment]
@marci4 Hey! Sorry. Not sure what was the issue. I just had to kill the process the first time and restarted again. The socket connections are working seamlessly. Thanks for checking back.
