### ISSUE TITLE
How to prevent WebsocketNotConnectedException?

### ISSUE THREAD

**Issue by casolorz** [TooTallNate/Java-WebSocket#638]
I'm using 1.3.6 on Android. For some reason I get this exception for some of my users:
```
Fatal Exception: aqg
       at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:598)
       at org.java_websocket.WebSocketImpl.sendFrame(WebSocketImpl.java:624)
       at org.java_websocket.WebSocketImpl.sendPing(WebSocketImpl.java:631)
       at org.java_websocket.AbstractWebSocket$1.run(AbstractWebSocket.java:142)
       at java.util.Timer$TimerImpl.run(Timer.java:284)
```
Seems to happen here:

```
private void send( Collection<Framedata> frames ) {
		if( !isOpen() ) {
			throw new WebsocketNotConnectedException();
		}
```

Is there a way I can prevent this from happening from my code? I'm guessing I'm sending something without checking for a connection first or something? Whatever is happening, I should be able to report to the user an error or try to recover, instead of crashing.

Thank you.

**Comment by marci4** [comment]
Hello @casolorz,

Could you maybe update to 1.3.7 and check if this issue still exists for you?

Greetings
marci4

**Comment by casolorz** [comment]
Sure, it'll be a bit before I know as I've never reproduced it but I'll try it with my beta users soon. We can close this and I can reopen it if it doesn't help.
