### ISSUE TITLE
Client crashing with WebsocketNotConnectedException 

### ISSUE THREAD

**Issue by lavancfc** [TooTallNate/Java-WebSocket#658]
This is My code

public class WsClientActivity extends AppCompatActivity {

    public WsClient c=null;
    public Button var_btn_connectwss;
    public EditText var_et_WSIP;
    public EditText var_et_WSPORT;
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_wsclient);

         var_et_WSIP = findViewById(R.id.id_et_WSIP);
         var_et_WSPORT = findViewById(R.id.id_et_WSPORT);
         var_btn_connectwss = findViewById(R.id.id_btn_connectwss);

        try {
           c = new WsClient(new URI("ws://192.168.0.106:8877"));
        } catch (NotYetConnectedException e) {
            e.printStackTrace();
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }

    public void onGroupRadioButtonClicked(View v) {
        RadioButton var_rb_G1 =  findViewById(R.id.id_rb_G1);
        boolean  checked = ((RadioButton) v).isChecked();
        switch(v.getId()) {

            case R.id.id_rb_G1:
                if (checked)
               
                 c.send("1");
               break;

## Debug log (for bugs)

FATAL EXCEPTION: main
Process: com.zinco.Zinco_BK_WsClient, PID: 7265                                                                           java.lang.IllegalStateException: Could not execute method for android:onClick
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick
(AppCompatViewInflater.java:293)
at android.view.View.performClick(View.java:6256)
at android.widget.CompoundButton.performClick(CompoundButton.java:134)
at android.view.View$PerformClick.run(View.java:24701)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:172)
at android.app.ActivityThread.main(ActivityThread.java:6637)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick
(AppCompatViewInflater.java:288)
at android.view.View.performClick(View.java:6256) 
at android.widget.CompoundButton.performClick(CompoundButton.java:134) 
at android.view.View$PerformClick.run(View.java:24701) 
at android.os.Handler.handleCallback(Handler.java:789) 
at android.os.Handler.dispatchMessage(Handler.java:98) 
at android.os.Looper.loop(Looper.java:172) 
at android.app.ActivityThread.main(ActivityThread.java:6637) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
Caused by: org.java_websocket.exceptions.WebsocketNotConnectedException
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:207)
at com.zinco.bk.WsClientActivity.onGroupRadioButtonClicked(WsClientActivity.java:83)
at java.lang.reflect.Method.invoke(Native Method) 
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick
(AppCompatViewInflater.java:288) 
at android.view.View.performClick(View.java:6256) 
at android.widget.CompoundButton.performClick(CompoundButton.java:134) 
 at android.view.View$PerformClick.run(View.java:24701) 
 at android.os.Handler.handleCallback(Handler.java:789) 
at android.os.Handler.dispatchMessage(Handler.java:98) 
at android.os.Looper.loop(Looper.java:172) 
 at android.app.ActivityThread.main(ActivityThread.java:6637) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 

## Context

I want the application UI working even if there is no websocket conection

## Your Environment
Java WS Version used:1.3.7
* Operating System and version: android oreo

**Comment by marci4** [comment]
Hello @lavancfc,

you can check with [isOpen()](https://static.javadoc.io/org.java-websocket/Java-WebSocket/1.3.7/org/java_websocket/client/WebSocketClient.html#isOpen--) if the connection is established.

Greetings
marci4

**Comment by lavancfc** [comment]
Thank you @marci4 .
Issue Resolved.
Please close
