### ISSUE TITLE
NPE when address already in use

### ISSUE THREAD

**Issue by bcersows** [TooTallNate/Java-WebSocket#661]
## Expected Behavior
When the port to used is already blocked, shut down the websocket again, eventually notifying the caller that it failed as well.

## Current Behavior
A NullPointerException in the `stop()` method is thrown when the server-side binding failed because the address/socket is used already.

## Possible Solution
Add a non-null check before calling `selector.wakeup();`.

## Steps to Reproduce (for bugs)
1. Open a server websocket
2. Open a new server websocket on the same port again

## Debug log (for bugs)

```
2018-Feb-05 10:48:00 AM [WebsocketSelector28] ERROR application.websockets.WebsocketServer - an error occured:java.net.BindException: Address already in use: bind
Exception in thread "WebsocketSelector28" java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:257)
	at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:263)
	at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:539)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:321)
	at java.lang.Thread.run(Thread.java:748)
```

The error line is

```
synchronized ( this ) {
	if( selectorthread != null  ) {
--->		selector.wakeup();
		selectorthread.join( timeout );
	}
}
```

## Your Environment

* Version used: 1.3.7
* Java version: Java 8.161
* Operating System and version: Win10

**Comment by marci4** [comment]
Hello @bcersows,

thank you for your bug report.

Fixed this issue with #662.

Greetings
marci4
