### ISSUE TITLE
CPU High Usage

### ISSUE THREAD

**Issue by lifubang** [TooTallNate/Java-WebSocket#687]
My WebSocket Server is crashed.
```
root@da1b288ef0e6:/# top
top - 01:37:52 up 9 days, 13:41,  0 users,  load average: 1.19, 1.12, 1.03
Tasks:  12 total,   1 running,  11 sleeping,   0 stopped,   0 zombie
%Cpu0  : 31.1 us,  8.3 sy,  0.0 ni, 60.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  : 46.3 us, 15.3 sy,  0.0 ni, 38.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   4046408 total,  2606988 used,  1439420 free,   422932 buffers
KiB Swap:        0 total,        0 used,        0 free.  1224764 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                     
 3346 root      20   0 2312708 593592  16544 S 100.2 14.7 839:31.30 java                                                        
    1 root      20   0   32972   3492   2640 S   0.0  0.1   0:00.11 init                                                        
   31 root      20   0   26504   2204   1984 S   0.0  0.1   0:00.00 plymouthd                                                   
   34 root      20   0   19556   2148   1812 S   0.0  0.1   0:00.24 plymouth-upstar                                             
   35 root      20   0   19408    180      0 S   0.0  0.0   0:00.00 ureadahead                                                  
 3115 root      20   0   19476    176      0 S   0.0  0.0   0:00.00 upstart-udev-br                                             
 3128 root      20   0   49272   3128   2704 S   0.0  0.1   0:00.00 systemd-udevd                                               
 3150 root      20   0   15276    228      0 S   0.0  0.0   0:00.00 upstart-file-br                                             
 3152 syslog    20   0  190308   2684   2260 S   0.0  0.1   0:00.07 rsyslogd                                                    
 3324 root      20   0   18216   3412   2880 S   0.0  0.1   0:00.00 bash                                                        
 3390 root      20   0   18216   3376   2856 S   0.0  0.1   0:00.00 bash                                                        
 3420 root      20   0   19876   2464   2108 R   0.0  0.1   0:00.00 top
```
```
ps -mp 3346 -o THREAD,tid,time
USER     %CPU PRI SCNT WCHAN  USER SYSTEM   TID     TIME
root      100   -    - -         -      -     - 14:00:02
root      0.0  19    - futex_    -      -  3346 00:00:00
root      0.0  19    - futex_    -      -  3347 00:00:04
root      0.1  19    - futex_    -      -  3348 00:01:28
root      0.1  19    - futex_    -      -  3349 00:01:28
root      0.1  19    - futex_    -      -  3350 00:01:06
root      0.0  19    - futex_    -      -  3351 00:00:00
root      0.0  19    - futex_    -      -  3352 00:00:00
root      0.0  19    - futex_    -      -  3353 00:00:00
root      0.0  19    - futex_    -      -  3354 00:00:07
root      0.0  19    - futex_    -      -  3355 00:00:07
root      0.0  19    - futex_    -      -  3356 00:00:00
root      0.0  19    - futex_    -      -  3357 00:00:25
root      0.0  19    - futex_    -      -  3358 00:00:09
root      0.0  19    - futex_    -      -  3359 00:00:09
root      0.0  19    - futex_    -      -  3363 00:00:02
root      0.0  19    - futex_    -      -  3364 00:00:06
root      0.0  19    - futex_    -      -  3365 00:00:05
root     99.5  19    - -         -      -  3366 13:53:33
root      0.0  19    - futex_    -      -  3367 00:00:01
root      0.1  19    - futex_    -      -  3369 00:01:05
root@da1b288ef0e6:/# printf "%x\n" 3366
d26
```
```
jstack 3346 | grep d26 -A 20 -B 10
	at java.lang.Thread.run(Thread.java:745)

"Timer-0" prio=10 tid=0x00007fdb88021800 nid=0xd27 in Object.wait() [0x00007fdba02fd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000c275df50> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000000c275df50> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)
*********************************************************************************************
d26 is here
*********************************************************************************************
"WebsocketSelector17" prio=10 tid=0x00007fdbd092c800 nid=**0xd26** runnable [0x00007fdba01fc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollCtl(Native Method)
	at sun.nio.ch.EPollArrayWrapper.updateRegistrations(EPollArrayWrapper.java:299)
	- locked <0x00000000c29b2fa0> (a java.lang.Object)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:268)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x00000000c29b2f28> (a sun.nio.ch.Util$2)
	- locked <0x00000000c29b2f18> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000c275e6b8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:316)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marci4** [comment]
Hello @lifubang,

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

Greetings
marci4

**Comment by lifubang** [comment]
Sorry, I use a nodejs ws library now.
