### ISSUE TITLE
Exception in thread "main" org.java_websocket.exceptions.WebsocketNotConnectedException

### ISSUE THREAD

**Issue by MatthiasKuk** [TooTallNate/Java-WebSocket#693]
## Expected Behavior
Connect to the server, send the message, close the connection

## Current Behavior
It seems like the client tries to send the message before connecting to the server. I get the following:
```
Exception in thread "main" org.java_websocket.exceptions.WebsocketNotConnectedException
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
	at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:309)
	at com.kuklinski.App.main(App.java:9)
```

As well as a **follow up(!)** answer by the server, which I configured on my backend(node.js).

For some reason, if I use a modified version of the method `send()`, for example `sendJSON()`, which embeds `send()`, I get the expected behaviour as describved above: the client connects to the server, sends the message via `sendJSON()` and closes the connection.

## Possible Solution
None, currently. I can't explain the mentioned behavior above.

## Steps to Reproduce (for bugs)
**Class App**
```
public class App {
  public static void main(String[] args) throws Exception{
    WebSocket ws = new WebSocket(new URI("ws://127.0.0.1:8080"));
    ws.connect();
    ws.send("Some message");
    ws.close();
  }
}
```
Class WebSocket (includes `sendJSON()` )
```
import com.google.gson.Gson;
import org.java_websocket.client.WebSocketClient;
import org.java_websocket.handshake.ServerHandshake;

import java.net.URI;


// Connects and interacts with a server via a WebSocket
class WebSocket extends WebSocketClient {
  // Inherited Constructor
  WebSocket(URI serverURI) {
    super(serverURI);
  }

  @Override
  public void onOpen(ServerHandshake serverHandshake) {
    send("Client connected successfully");
  }

  @Override
  public void onMessage(String msg) {
    System.out.println("Received(server): " + msg);
  }

  @Override
  public void onClose(int code, String reason, boolean remote) {
    System.out.println("Connection closed with exit code " + code + ", additional info: " + reason);
  }

  @Override
  public void onError(Exception e) {
    e.printStackTrace();
  }

  Object sendJSON(Object data) {
    send(new Gson().toJson(data));
    return data;
  }
}
```

## Debug log (for bugs)
```
Exception in thread "main" org.java_websocket.exceptions.WebsocketNotConnectedException
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
	at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:309)
	at com.kuklinski.App.main(App.java:12)
write(153): {GET / HTTP/1.1
Connection: Upgrade
Host: 127.0.0.1:8080
Sec-WebSocket-Key: q6W4XEf6DX9UIpwIKlq4Iw==
Sec-WebSocket-Version: 13
Upgrade: websocket

}
process(129): {HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: 3LRUa2oG45Exz+A/B0v+Li4OsK4=

}
open using draft: Draft_6455 extension: DefaultExtension protocol: 
Connection lost timer started
send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:29], payload:Client connected successfully}
afterEnconding(29): {Client connected successfully}
write(35): {��mS4�.?]�'�=Z�'Q�M A�6G�&X�}
process(36): {�"You are connected to the WebSocket}
afterDecoding(34): {You are connected to the WebSocket}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:34], payload:You are connected to the WebSocket}
Received(server): You are connected to the WebSocket
```

## Context
I'm trying to use a WebSocket.

## Your Environment
**Gradle.build**
```
group 'com.kuklinski'
version '1.0.0'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

jar {
    manifest {
        attributes 'Implementation-Title': 'Binocularis-Remoteclient',
                'Implementation-Version': version,
                'Main-Class': 'com.kuklinski.App'
    }

    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

dependencies {
    // https://mvnrepository.com/artifact/junit/junit
    testCompile group: 'junit', name: 'junit', version: '4.12'
    // https://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket
    compile group: 'org.java-websocket', name: 'Java-WebSocket', version: '1.3.8'
    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.2'
}
```

**Comment by marci4** [comment]
Hello @MatthiasKuk,

for your first question please check out the FAQ in the wiki!

For the follow up question, I quess that this just takes longer to process the json or is async and therefore the connection is already established!

Best regards,

marci4

**Comment by marci4** [comment]
No feedback for a week!

Issue should be answered from my point of view!

Closing it!
Best regards,
marci4
