### ISSUE TITLE
Handshake fails while connecting from Edge Browser - Microsoft Edge 42.17134.1.0

### ISSUE THREAD

**Issue by mani2478** [TooTallNate/Java-WebSocket#720]
Connecting secure websocker server fails while trying from Edge Browser Microsoft Edge 42.17134.1.0.

## Expected Behavior
Expected like other browsers.

## Current Behavior
java.io.IOException: connection closed unexpectedly by peer

## Possible Solution
No Work Around

## Steps to Reproduce (for bugs)
1.Used the java -cp build/examples;dist/java_websocket.jar -Djavax.net.debug=all SSLServerExample and connected the secure websocket server from http://www.websocket.org/echo.html

## Debug log (for bugs)
Error Message:connection closed unexpectedly by peer
java.io.IOException: connection closed unexpectedly by peer
        at org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:166)
        at org.java_websocket.SSLSocketChannel2.write(SSLSocketChannel2.java:252)
        at org.java_websocket.SSLSocketChannel2.writeMore(SSLSocketChannel2.java:396)
        at org.java_websocket.SocketChannelIOHelper.batch(SocketChannelIOHelper.java:82)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:428)
        at java.lang.Thread.run(Unknown Source)
WebSocketSelector-14, called closeOutbound()
WebSocketSelector-14, closeOutboundInternal()
WebSocketSelector-14, SEND TLSv1.2 ALERT:  warning, description = close_notify
WebSocketSelector-14, WRITE: TLSv1.2 Alert, length = 2
[Raw write]: length = 7
0000: 15 03 03 00 02 01 00                               .......
java.lang.Exception: Stack trace
        at java.lang.Thread.dumpStack(Unknown Source)
        at org.java_websocket.server.WebSocketServer.removeConnection(WebSocketServer.java:618)
        at org.java_websocket.server.WebSocketServer.onWebsocketClose(WebSocketServer.java:596)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:543)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:565)
        at org.java_websocket.server.WebSocketServer.handleIOException(WebSocketServer.java:532)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:460)
        at java.lang.Thread.run(Unknown Source)
Removing connection which is not in the connections collection! Possible no handshake recieved! org.java_websocket.WebSocketImpl@e319555

## Your Environment

* Version used:
* Java version:
* Operating System and version:
* Endpoint Name and version:
* Link to your project:

**Comment by marci4** [comment]
Hello @mani2478,

I cannot reproduce this issue with Edge 41.16299.492.0.

Since you cannot install a new version manually, I have to mark this as cannot reproduce!

Best regards,
marci4

**Comment by marci4** [comment]
Hello @mani2478,

thank you for taking a look at this!

Best regards,
marci4
