### ISSUE TITLE
Can't close Server in OnClick

### ISSUE THREAD

**Issue by MuspelWolf** [TooTallNate/Java-WebSocket#728]
I'm trying to close the server when clicking a button in Android but the app get an error.
Android SDK version :21
Language : Java

Error in function call : 

public void stopVoiceRecognition () {
        if (speech != null) {
                speech.stopListening();
                speech.cancel();
                speech.destroy();
                speech = null;
                webSocket.closeConnection(1100,"Socket closed");
        }
    }

**Comment by PhilipRoman** [comment]
Can you post a stack trace here?

**Comment by MuspelWolf** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.raulgarcia.bsbandriod, PID: 2417
                  java.lang.IllegalStateException: Could not execute method for android:onClick
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:389)
                      at android.view.View.performClick(View.java:5647)
                      at android.view.View$PerformClick.run(View.java:22465)
                      at android.os.Handler.handleCallback(Handler.java:754)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:163)
                      at android.app.ActivityThread.main(ActivityThread.java:6396)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Method.invoke(Native Method)
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384)
                      at android.view.View.performClick(View.java:5647) 
                      at android.view.View$PerformClick.run(View.java:22465) 
                      at android.os.Handler.handleCallback(Handler.java:754) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:163) 
                      at android.app.ActivityThread.main(ActivityThread.java:6396) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
                   Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.java_websocket.WebSocket.closeConnection(int, java.lang.String)' on a null object reference
                      at com.example.raulgarcia.bsbandriod.Room.stopVoiceRecognition(Room.java:148)
                      at com.example.raulgarcia.bsbandriod.Room.ButtonStopEvent(Room.java:102)
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384) 
                      at android.view.View.performClick(View.java:5647) 
                      at android.view.View$PerformClick.run(View.java:22465) 
                      at android.os.Handler.handleCallback(Handler.java:754) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:163) 
                      at android.app.ActivityThread.main(ActivityThread.java:6396) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by PhilipRoman** [comment]
Okay, this might be really stupid from me, but is it possible that `webSocket` variable is null at the time when you try to close it? 

The line `Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.java_websocket.WebSocket.closeConnection(int, java.lang.String)' on a null object reference` seems to suggest that.

**Comment by MuspelWolf** [comment]
Just fixed the error, changed WebSocket to Server class to close the connection.
Thanks for the help.
