### ISSUE TITLE
reconnect() NullPointerException

### ISSUE THREAD

**Issue by 0xZhangKe** [TooTallNate/Java-WebSocket#745]
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Thread.getId()' on a null object reference
	at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:269)
	at org.java_websocket.client.WebSocketClient.reconnect(WebSocketClient.java:222)
	at com.xx.websocket.WebSocketThread$WebSocketHandler.connect(WebSocketThread.java:172)
	at com.xx.websocket.WebSocketThread$WebSocketHandler.handleMessage(WebSocketThread.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:232)
	at com.xx.websocket.WebSocketThread.run(WebSocketThread.java:60)

**Comment by 0xZhangKe** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.start()' on a null object reference
	at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:270)
	at org.java_websocket.client.WebSocketClient.reconnect(WebSocketClient.java:222)
	at com.xx.websocket.WebSocketThread$WebSocketHandler.connect(WebSocketThread.java:172)
	at com.xx.websocket.WebSocketThread$WebSocketHandler.handleMessage(WebSocketThread.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:232)
	at com.xx.websocket.WebSocketThread.run(WebSocketThread.java:60)

**Comment by PhilipRoman** [comment]
Thanks for catching this error! It would be nice if you could add additional information to match the [issue template](https://github.com/TooTallNate/Java-WebSocket/blob/master/.github/ISSUE_TEMPLATE.md), especially the steps to reproduce and android/java version to make it easier to solve this issue.

**Comment by 0xZhangKe** [comment]
Model：Meizu MX6 and OPPO A83T；
System version：Android 7.1.1
Java-WebSocke versiont：1.3.8

I don't know the steps，It`s from  Umeng  analytics. 
Maybe it's because reconnect() calls many times.

**Comment by PhilipRoman** [comment]
By the way, are you sure that only one thread accesses the WebSocketClient object and calls connect/reconnect? It could be a race condition where the socket is reset while being connected.

**Comment by 0xZhangKe** [comment]
@PhilipRoman Yes, only one thread .

**Comment by marci4** [comment]
Any update?

**Comment by 0xZhangKe** [comment]
Sorry,I have never recovered this bug.

**Comment by marci4** [comment]
No steps to repeat! No template! And cannot reproduce by reporter....

Closing issue!
Best regards,
marci4
