### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by yangxsa** [TooTallNate/Java-WebSocket#752]
hi,i want to connect 'wss://www.bitmex.com/realtime'
I met this question.
Mmay I ask what I can do to ignore the SSL certificate?
Maybe there's something wrong with my code.
```
public static void main(String[] args) throws URISyntaxException {
        ExampleClient c = new ExampleClient(new URI("wss://www.bitmex.com/realtime"));
        c.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 1080)));
        c.connect();
    }
```

**Comment by yangxsa** [comment]
This is complete log

Connection closed by remote peer Code: -1 Reason: 
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:980)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:916)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.InputStream.read(InputStream.java:101)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:416)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961)
	... 6 more
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:980)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:916)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.InputStream.read(InputStream.java:101)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:416)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961)
	... 6 more

**Comment by marci4** [comment]
Hello @yangxsa 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

Also why do you reqire a local http proxy?

Best regards,
marci4

**Comment by yangxsa** [comment]
I am in China,but the url "wss://www.bitmex.com/realtime" is  not available in China.
I used vpn，so I add a local http proxy,and i am wrong?
I can't understand why i am faild
I try to connected "wss://api.fcoin.com/v2/ws" just now,i am success
Originally, I think is SSL certificate not correct,but now....
Sorry,English is not good
Thanks for your view and reply.

**Comment by marci4** [comment]
Please use the template!

Otherwise this issue will be closed...

**Comment by marci4** [comment]
No template. Closing issue...

Best regards,
marci4
