### ISSUE TITLE
NullpointException：connect 

### ISSUE THREAD

**Issue by xiejinsorry** [TooTallNate/Java-WebSocket#791]
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.start()' on a null object reference
	at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:284)
	at org.java_websocket.client.WebSocketClient.connectBlocking(WebSocketClient.java:293)
	at org.java_websocket.client.WebSocketClient.reconnectBlocking(WebSocketClient.java:239)
	onNetReconnect(IMClient.java:224)

**Comment by ristodziuba** [comment]
Why closed? I have this same error. What info you need?

**Comment by marci4** [comment]
What should I do with an issue without steps to reproduce, no template used, to example application, nothing?

**Comment by tongshendota** [comment]
I also encountered this problem

Attempt to invoke virtual method 'void java.lang.Thread.start()' on a null object reference

**Comment by PhilipRoman** [comment]
@tongshendota please post code which shows the problem.
Also, what OS, library version, and Java version are you using?
