### ISSUE TITLE
Deadlock when calling WebSocketImpl.close()

### ISSUE THREAD

**Issue by FlorentMasson** [TooTallNate/Java-WebSocket#798]
**Describe the bug**
One of my thread tries to close a socket because it's inactive, but another thread simultaneously handles the onClose event and they deadlock themselves

What bothers me is the "synchronized" declaration [here ](https://github.com/TooTallNate/Java-WebSocket/blob/587a0adb27d7b2f806554b818fe8c8c3971514ed/src/main/java/org/java_websocket/WebSocketImpl.java#L415) **before** testing if the socket is already closed.

Shoudn't the socket close status be tested beforehand, for instance in the close() function [here](https://github.com/TooTallNate/Java-WebSocket/blob/587a0adb27d7b2f806554b818fe8c8c3971514ed/src/main/java/org/java_websocket/WebSocketImpl.java#L772)?

Here is the thread stacktrace

```
Found one Java-level deadlock:
=============================
"WebSocketTimer":
  waiting to lock monitor 0x00007fe474005248 (object 0x00000000c2bab6c0, a java.lang.Object),
  which is held by "Thread-2"
"Thread-2":
  waiting to lock monitor 0x00007fe454004128 (object 0x00000000c3a47098, a org.java_websocket.WebSocketImpl),
  which is held by "WebSocketSelector-11"
"WebSocketSelector-11":
  waiting to lock monitor 0x00007fe474005248 (object 0x00000000c2bab6c0, a java.lang.Object),
  which is held by "Thread-2"

Java stack information for the threads listed above:
===================================================
"WebSocketTimer":
        at xxx.yyy.removePlayer(yyy.java:593)
        - waiting to lock <0x00000000c2bab6c0> (a java.lang.Object)
        at xxx.zzz.onClose(zzz.java:188)
        at org.java_websocket.server.WebSocketServer.onWebsocketClose(WebSocketServer.java:595)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:504)
        - locked <0x00000000c4c977d0> (a org.java_websocket.WebSocketImpl)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:526)
        at org.java_websocket.AbstractWebSocket$1.run(AbstractWebSocket.java:176)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
"Thread-2":
        at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:416)
        - waiting to lock <0x00000000c3a47098> (a org.java_websocket.WebSocketImpl)
        at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:569)
        at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:773)
        at xxx.ConnectedPlayer.closeForInactivity(ConnectedPlayer.java:229)
        at xxx.ConnectedPlayer.activityCheck(ConnectedPlayer.java:214)
        at xxx.yyy.resolvePlayingTurn(yyy.java:1925)
        at xxx.yyy.run(yyy.java:876)
        - locked <0x00000000c2bab6c0> (a java.lang.Object)
"WebSocketSelector-11":
        at xxx.yyy.removePlayer(yyy.java:593)
        - waiting to lock <0x00000000c2bab6c0> (a java.lang.Object)
        at xxx.zzz.onClose(zzz.java:188)
        at org.java_websocket.server.WebSocketServer.onWebsocketClose(WebSocketServer.java:595)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:504)
        - locked <0x00000000c3a47098> (a org.java_websocket.WebSocketImpl)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:522)
        at org.java_websocket.SocketChannelIOHelper.batch(SocketChannelIOHelper.java:99)
        - locked <0x00000000c3a47098> (a org.java_websocket.WebSocketImpl)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:428)
        at java.lang.Thread.run(Thread.java:748)

```

**Expected behavior**
WebSocketImpl.close() should not lock the websocket object if closed already and should just return

**Environment(please complete the following information):**
 - Version used: 1.3.9
 - Java version: 1.8.0_161 (Oracle)
 - Operating System and version: Ubuntu 16.04

**Comment by marci4** [comment]
Hello @FlorentMasson,

thank you for your bug report.

Do you think you can provide an example application so I can write a Unit test for this issue?

Thank you!

Best regards,
marci4

**Comment by marci4** [comment]
Dead issue.

Closing it .

Best regards,
Marcel
