### ISSUE TITLE
Buffer Underflow when content coming from a websocket client is too long

### ISSUE THREAD

**Issue by newsbubbles** [TooTallNate/Java-WebSocket#853]
**Describe the bug**

When using the WebsocketServer and connected to a websockets client, there is an issue when the response from the client is too long.  It looks like some sort of a buffering issue.

**To Reproduce**
1. start the WebsocketServer
2. connect via a client
3. send a string of data from the client to the server that is longer than 2048 bytes

**Example application to reproduce the issue**
I have none here...

**Expected behavior**
Server receives the string and continues connection

**Debug log**

[WebSocketWorker-14] ERROR org.java_websocket.server.WebSocketServer - Error while reading from remote connection
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Unknown Source)
	at java.nio.HeapByteBuffer.get(Unknown Source)
	at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:491)
	at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:628)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:378)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:218)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1009)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:991)

**Environment(please complete the following information):**
 - Version used: Latest, downloaded 2019-01-09
 - Java version: 8
 - Operating System and version: Windows 8.1
 - Endpoint Name and version:
 - Link to your project:

**Additional context**

I did some testing around, the 2048 length string is a guess... but for instance, everything works fine when the string is smaller than 255

**Comment by PhilipRoman** [comment]
Can you attempt to reproduce with latest library version? You're probably observing the effects of bug #847 which lasted from Nov 11, 2018 to Feb 5, 2019.

**Comment by newsbubbles** [comment]
Yes, I will attempt reproduce now... nice answer time an thanks a lot for such great support!

**Comment by newsbubbles** [comment]
Great it works for me, thanks!
