### ISSUE TITLE
org.java_websocket.exceptions.WebsocketNotConnectedException

### ISSUE THREAD

**Issue by xiaohaixiangqianchong** [TooTallNate/Java-WebSocket#895]
I  used org.java-websocket:Java-WebSocket:1.3.7 ,our app has this crash 
"org.java_websocket.exceptions.WebsocketNotConnectedException
    at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
    at org.java_websocket.WebSocketImpl.sendFrame(WebSocketImpl.java:634)
    at org.java_websocket.WebSocketImpl.sendPing(WebSocketImpl.java:641)
    at org.java_websocket.AbstractWebSocket$1.run(AbstractWebSocket.java:153)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)",

Is this a bug has resovled in Java-WebSocket:1.4.0?

**Comment by maiph** [comment]
It appears that you didn't succeed to connect to the server. 
Did you call `WebSocketClient.connect()` before sending data? If so can you post an example to reproduce the error?

**Comment by marci4** [comment]
I think this issue duplicates #715

**Comment by marci4** [comment]
Closing this issue as duplicate.

Best regards,
Marcel
