### ISSUE TITLE
Server Connection Error

### ISSUE THREAD

**Issue by GipfelStudios** [TooTallNate/Java-WebSocket#911]
**Describe the bug**
If I try to connect, to my Server the client disconnect. I tryed with https://www.websocket.org and with a own script. Nothing work and the client dosen't get a error. 
The Server get this Error:

```
2019-06-21 13:49:49.669 [TRACE] Connection closed because of exception
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:309)
        at org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:42)
        at org.java_websocket.server.WebSocketServer.doRead(WebSocketServer.java:458)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:348)
        at java.lang.Thread.run(Thread.java:748)
```

I use this SSLContext code: https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLServerExample.java

**Environment(please complete the following information):**
 - Version used: 1.4.0 / Java 8
 - Java version: openjdk version "1.8.0_212", 
 - Operating System and version: Debian 9 (stretch)

**Comment by marci4** [comment]
Hello @GipfelStudios,

please provide an example application for both the client and the server.

I am not sure why both client and server should be affected and I can also use the normal client example to connect to wss://echo.websocket.org.

Best regards,
Marcel

**Comment by GipfelStudios** [comment]
Here my code:

Main:
```
public class Main{
	
	public static Server mserver;
	

	public static void main(String[] args) {
		
		
		int port = 9999;
	
		
		try {
		String STORETYPE = "JKS";
		String KEYSTORE = "keystore.jks";
		String STOREPASSWORD = "passwd";
		String KEYPASSWORD = "passwd";

		KeyStore ks = KeyStore.getInstance( STORETYPE );
		File kf = new File( KEYSTORE );
		ks.load( new FileInputStream( kf ), STOREPASSWORD.toCharArray() );

		KeyManagerFactory kmf = KeyManagerFactory.getInstance( "SunX509" );
		kmf.init( ks, KEYPASSWORD.toCharArray() );
		TrustManagerFactory tmf = TrustManagerFactory.getInstance( "SunX509" );
		tmf.init( ks );

		SSLContext sslContext = null;
		sslContext = SSLContext.getInstance( "TLS" );
		sslContext.init( kmf.getKeyManagers(), tmf.getTrustManagers(), null );
	    Server server = new Server(port);
	    
	    server.setWebSocketFactory(new DefaultSSLWebSocketServerFactory( sslContext ));
	    
	    mserver = server;
	    
	    server.start();
	    
		} catch (KeyStoreException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (NoSuchAlgorithmException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (CertificateException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (UnrecoverableKeyException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (KeyManagementException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
			
			@Override
			public void run() {
				//ShutdownHook
			}
			
		}));
		
		
	}

	
	
	
	

}
```


Server.java: 

```

import java.net.InetSocketAddress;
import java.net.UnknownHostException;

import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

public class Server extends WebSocketServer{
	
	public Server( int port ) throws UnknownHostException {
		super( new InetSocketAddress( port ) );
	}

	public Server( InetSocketAddress address ) {
		super( address );
	}
	
	
	
	
	@Override
	public void onClose(WebSocket socket, int ErrCode, String reason, boolean remote) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onError(WebSocket socket, Exception exception) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onMessage(WebSocket socket, String message) {
		socket.send("R");
		
	}

	@Override
	public void onOpen(WebSocket socket, ClientHandshake handshake) {
		socket.send("Connected");
		
	}

	@Override
	public void onStart() {
		System.out.println("Started!");
		
	}

}
```


Socket Client Example:
```

		<script>
		try {
			var socket = new WebSocket("wss://url.com:9999");

			socket.onmessage = function (event) {
			var msg = JSON.parse(event.data);
			console.log(msg);
			}

			socket.onopen = function (event) {
				console.log("Connected");
			};

		}catch(ex){
			console.log(ex);
		}
		
		
		</script>
```


Best regards,
Markus

**Comment by marci4** [comment]
Hello Markus,

I quess you have a self signed certificate?
Have you trusted it in your webbrowser (open https://url.com:9999 and acknowledge the security warning and then it should be fine)?
Is your certificate issued for url.com?

Best regards,
Marcel

**Comment by GipfelStudios** [comment]
Oh okay. Yes the certificate was the reason. Sorry.

Best regards
Markus

**Comment by marci4** [comment]
Closing this issue as solved!

Best regards,
Marcel
