### ISSUE TITLE
Trying SSL wws with LetsEncrypt connection hangs after first or second connection

### ISSUE THREAD

**Issue by fatrolls** [TooTallNate/Java-WebSocket#986]
Ya I still have this issue with WebSocket-Java 1.4.1

Firstly it says

`String password = "changeit";`

I tried changing it and it still works, I tried a blank password because my LetsEncrypt doesn't use any passwords I did some research and found out JKS or PKCS12 is required for java i couldn't understand it all do I need to run a keytool or openssl at all? or just use the certs that come from certbot?. Either way I use a password or I don't it still works.. but it only works like for 2 connections then it hangs and doesn't allow any new connections for a while.

Can you tell me exactly how do it for LetsEncrypt certs that I use on apache/httpd without converting them or anything? that's what I thought it would use. I have absolutely no problem running the WebSockets without wws:// just ws:// no hangs nothing.

My current code

```
       try {
            //Start WebSockets Server
            ws = new WSServer( ChatServer.CHAT_SERVER_PORT );

            if(useSSL) {
                SSLContext context = getContext();
                if( context != null )
                    ws.setWebSocketFactory( new DefaultSSLWebSocketServerFactory( getContext() ) );

                //Reload SSL Certificates every 24 hours, in case they need renewal.
                Timer timer = new Timer ();
                TimerTask t = new TimerTask () {
                    @Override
                    public void run () {
                    System.out.println("WTF this hangs my connections if I call ws.setWebSocketFactory() twice??");
                   //never mind it always hangs even if I call it one time.
                    /*
                        SSLContext context = getContext();
                        if( context != null )
                            ws.setWebSocketFactory( new DefaultSSLWebSocketServerFactory( getContext() ) );
                    */
                    }
                };
                timer.schedule (t, 0L, 1000*60*60*24);
            }

            ws.start();
            System.out.println( "Starting WebSocket Chat Server on port: " + ws.getPort() + " with SSL=" + useSSL );
        } catch(UnknownHostException uhe) {
            System.out.println("WebSocketsServer starting Exception = " + uhe.getMessage());
        }
    }

    private static SSLContext getContext() {
        SSLContext context;
        String password = "changeit";
        String pathname = "/etc/letsencrypt/live/mydomain.com";
        try {
            context = SSLContext.getInstance( "TLS" );

            byte[] certBytes = parseDERFromPEM( getBytes( new File( pathname + File.separator + "cert.pem" ) ), "-----BEGIN CERTIFICATE-----", "-----END CERTIFICATE-----" );
            byte[] keyBytes = parseDERFromPEM( getBytes( new File( pathname + File.separator + "privkey.pem" ) ), "-----BEGIN PRIVATE KEY-----", "-----END PRIVATE KEY-----" );

            X509Certificate cert = generateCertificateFromDER( certBytes );
            RSAPrivateKey key = generatePrivateKeyFromDER( keyBytes );

            KeyStore keystore = KeyStore.getInstance( "JKS" );
            keystore.load( null );
            keystore.setCertificateEntry( "cert-alias", cert );
            keystore.setKeyEntry( "key-alias", key, password.toCharArray(), new Certificate[] { cert } );

            KeyManagerFactory kmf = KeyManagerFactory.getInstance( "SunX509" );
            kmf.init( keystore, password.toCharArray() );

            KeyManager[] km = kmf.getKeyManagers();

            context.init( km, null, null );
        } catch ( Exception e ) {
            e.printStackTrace();
            context = null;
        }
        return context;
    }

    private static byte[] parseDERFromPEM( byte[] pem, String beginDelimiter, String endDelimiter ) {
        String data = new String( pem );
        String[] tokens = data.split( beginDelimiter );
        tokens = tokens[1].split( endDelimiter );
        return DatatypeConverter.parseBase64Binary( tokens[0] );
    }

    private static RSAPrivateKey generatePrivateKeyFromDER( byte[] keyBytes ) throws InvalidKeySpecException, NoSuchAlgorithmException {
        PKCS8EncodedKeySpec spec = new PKCS8EncodedKeySpec( keyBytes );

        KeyFactory factory = KeyFactory.getInstance( "RSA" );

        return ( RSAPrivateKey ) factory.generatePrivate( spec );
    }

    private static X509Certificate generateCertificateFromDER( byte[] certBytes ) throws CertificateException {
        CertificateFactory factory = CertificateFactory.getInstance( "X.509" );

        return ( X509Certificate ) factory.generateCertificate( new ByteArrayInputStream( certBytes ) );
    }

    private static byte[] getBytes( File file ) {
        byte[] bytesArray = new byte[( int ) file.length()];

        FileInputStream fis = null;
        try {
            fis = new FileInputStream( file );
            fis.read( bytesArray ); //read file into bytes[]
            fis.close();
        } catch ( IOException e ) {
            e.printStackTrace();
        }
        return bytesArray;
    }
```

I added slf4j simplelogger to see more detailed logging to see why connections hang in LetEncrypt SSL mode and here is what I got.

after adding to classpath

slf4j-api-1.7.22.jar
slf4j-simple-1.7.22.jar

with path to 
-Dorg.slf4j.simpleLogger.defaultLogLevel=debug
nothing shown
-Dorg.slf4j.simpleLogger.defaultLogLevel=trace
then this with trace
the logs show nothing about SSL

```
[root@highgamer Chat]# ./run.sh
WTF this hangs my connections if I call ws.setWebSocketFactory() twice
Starting WebSocket Chat Server on port: 5555 with SSL=true
2020-03-13 02:14:51.855 [TRACE] Connection lost timer started
Server started!
2020-03-13 02:14:51.872 [TRACE] Connection lost timer restarted
2020-03-13 02:14:52.580 [TRACE]
2020-03-13 02:14:52.583 [TRACE]
2020-03-13 02:14:53.054 [TRACE] process(751): (GET / HTTP/1.1
Host: camspark.com:5555
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Upgrade: websocket
Origin: https://www.camspark.com
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.1408349093.1581580169; __gads=ID=aed106fc7d382788:T=1581580185:S=ALNI_MZGcjLXoSe43V5xkJ9IAV_mqghacA; lhc_per={%22vid%22:%221bf0e2c94ba786daaea5%22%2C%22lhc_hnh%22:%221583296992%22%2C%22ex%22:15842}; _gid=GA1.2.1736209455.1583811256
Sec-WebSocket-Key: dJescYHHtWx56Ol9PhSzSw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

)
2020-03-13 02:14:53.065 [TRACE] acceptHandshakeAsServer - Matching extension found: DefaultExtension
2020-03-13 02:14:53.065 [TRACE] acceptHandshake - Matching protocol found:
2020-03-13 02:14:53.085 [TRACE] write(212): HTTP/1.1 101 Web Socket Protocol Handshake
Connection: Upgrade
Date: Fri, 13 Mar 2020 06:14:53 GMT
Sec-WebSocket-Accept: Y0cdwIk6+3pGC3ywHjADtJutmGQ=
Server: TooTallNate Java-WebSocket
Upgrade: websocket


2020-03-13 02:14:53.086 [TRACE] open using draft: Draft_6455 extension: DefaultExtension protocol:  max frame size: 2147483647
Server: Accepted from 68.197.137.241:63506
2020-03-13 02:14:53.130 [TRACE] process(19): (?????<???S???_????)
2020-03-13 02:14:53.140 [TRACE] afterDecoding(13): ["connected"]
2020-03-13 02:14:53.141 [TRACE] matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:13], payload:["connected"]}
2020-03-13 02:14:53.184 [TRACE] send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:25], payload:["userCount",[1,0,0,0,0]]}
2020-03-13 02:14:53.184 [TRACE] afterEnconding(25): ["userCount",[1,0,0,0,0]]
2020-03-13 02:14:53.184 [TRACE] write(27): ?["userCount",[1,0,0,0,0]]
2020-03-13 02:15:03.272 [TRACE] send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:25], payload:["userCount",[1,0,0,0,0]]}
2020-03-13 02:15:03.273 [TRACE] afterEnconding(25): ["userCount",[1,0,0,0,0]]
2020-03-13 02:15:03.273 [TRACE] write(27): ?["userCount",[1,0,0,0,0]]
2020-03-13 02:15:13.360 [TRACE] send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:25], payload:["userCount",[1,0,0,0,0]]}
2020-03-13 02:15:13.361 [TRACE] afterEnconding(25): ["userCount",[1,0,0,0,0]]
2020-03-13 02:15:13.361 [TRACE] write(27): ?["userCount",[1,0,0,0,0]]

```

after changing it back to non-SSL

I get these errors

```
2020-03-13 02:40:09.923 [TRACE] Removing connection which is not in the connections collection! Possible no handshake recieved! org.java_websocket.WebSocketImpl@41edb76f
2020-03-13 02:40:25.074 [TRACE] Removing connection which is not in the connections collection! Possible no handshake recieved! org.java_websocket.WebSocketImpl@288f75c9
```

I tested without SSL and on my production server (not local server) it was able to connect about 1000 times without any failures.. its definitely the SSL thats not accepting new connections.

I use this for testing 
https://chrome.google.com/webstore/detail/websocket-test-client/fgponpodhbmadfljofbimhhlengambbn?hl=en

Also after running the server in non-SSL mode after trying to connect to it with wws:// (SSL MODE) it would hang for 5 seconds on any new connections.. then it would start working normally again for non-SSL connections ws:// also is it possible to support both ws:// and wss:// on the same port?

Try running website that connects on SSL while you have WebSocket server running in non-SSL and try connecting with that chrome extension you will see it will take long to connect if your SSL site is connecting at the same time.

![test](https://i.imgur.com/Y8W4hwv.png)
(stuck like this on OPENING instead of OPENED for 5 seconds then it finally opens).

Here is how it looks when SSL connecting to non-SSL the packets come in messed up

```
2020-03-13 02:54:16.820 [TRACE] process(517): (??d????8?{??E??????lT??@vk??/? ^k**?X!J%*k???M?1:0k????jQOG"???+?/?,?0????????/5
???
camspark.com?
                                                                               ??                                                                            3+)?? ?????.CD????????u?L????
?kE-+



z?)
PuTTYPuTTYPuTTYPuTTYPuTTY2020-03-13 02:54:24.951 [TRACE] send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:25], payload:["userCount",[1,0,0,0,0]]}
```

**Comment by fatrolls** [comment]
I created a DNS Record to 127.0.0.1 on my domain for a subdomain and did a `certbot --expand` for a new subdomain.. copied the new certificate to my windows desktop `privkey.pem` and `cert.pem` and I modifed the javascript to connect to `wss://dev.xxx.com:5555` and spammed it with chrome extension `chrome-extension://fgponpodhbmadfljofbimhhlengambbn/index.html` It was doing fine.. better then my production server.. i was able to get like 500 connnections without any problems..

Then 1 connection failed and I got a exception but it didn't cause any hanging or anything just 1 websocket failure..

Here is the exception..

```
[WebSocketSelector-47] ERROR org.java_websocket.WebSocketImpl - Exception during channel.close()
java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
	at org.java_websocket.SSLSocketChannel2.close(SSLSocketChannel2.java:356)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:511)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:545)
	at org.java_websocket.server.WebSocketServer.handleIOException(WebSocketServer.java:608)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:361)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
	at org.java_websocket.SSLSocketChannel2.close(SSLSocketChannel2.java:356)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:511)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:545)
	at org.java_websocket.server.WebSocketServer.handleIOException(WebSocketServer.java:608)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:361)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

I was running the whole soruce code of Java-WebSocket together with my Chat server using Dr.Java to see if I could pinpoint the problem to why it hangs and I couldn't get it to hang on Windows, so it's most likely a problem with my host I guess.. I'll keep trying

```
disconnected
Server: Accepted from 127.0.0.1:58998
disconnected
Server: Accepted from 127.0.0.1:58999
disconnected
Server: Accepted from 127.0.0.1:59000
disconnected
Server: Accepted from 127.0.0.1:59001
disconnected
Server: Accepted from 127.0.0.1:59002
disconnected
Server: Accepted from 127.0.0.1:59003
disconnected
Server: Accepted from 127.0.0.1:59004
disconnected
Server: Accepted from 127.0.0.1:59005
disconnected
Server: Accepted from 127.0.0.1:59006
disconnected
Server: Accepted from 127.0.0.1:59007
disconnected
Server: Accepted from 127.0.0.1:59008
disconnected
Server: Accepted from 127.0.0.1:59009
disconnected
Server: Accepted from 127.0.0.1:59010
disconnected
Server: Accepted from 127.0.0.1:59011
disconnected
Server: Accepted from 127.0.0.1:59012
disconnected
Server: Accepted from 127.0.0.1:59013
disconnected
Server: Accepted from 127.0.0.1:59014
disconnected
Server: Accepted from 127.0.0.1:59015
disconnected
Server: Accepted from 127.0.0.1:59016
disconnected
Server: Accepted from 127.0.0.1:59017
disconnected
Server: Accepted from 127.0.0.1:59018
disconnected
Server: Accepted from 127.0.0.1:59019
disconnected
Server: Accepted from 127.0.0.1:59020
disconnected
Server: Accepted from 127.0.0.1:59021
disconnected
Server: Accepted from 127.0.0.1:59022
disconnected
Server: Accepted from 127.0.0.1:59023
disconnected
Server: Accepted from 127.0.0.1:59024
disconnected
Server: Accepted from 127.0.0.1:59025
disconnected
Server: Accepted from 127.0.0.1:59026
disconnected
Server: Accepted from 127.0.0.1:59027
disconnected
Server: Accepted from 127.0.0.1:59028
disconnected
Server: Accepted from 127.0.0.1:59029
disconnected
Server: Accepted from 127.0.0.1:59030
disconnected
Server: Accepted from 127.0.0.1:59031
disconnected
Server: Accepted from 127.0.0.1:59032
disconnected
Server: Accepted from 127.0.0.1:59033
disconnected
Server: Accepted from 127.0.0.1:59034
disconnected
Server: Accepted from 127.0.0.1:59035
disconnected
Server: Accepted from 127.0.0.1:59036
disconnected
Server: Accepted from 127.0.0.1:59037
disconnected
Server: Accepted from 127.0.0.1:59038
disconnected
Server: Accepted from 127.0.0.1:59039
disconnected
Server: Accepted from 127.0.0.1:59040
disconnected
Server: Accepted from 127.0.0.1:59041
disconnected
Server: Accepted from 127.0.0.1:59042
disconnected
Server: Accepted from 127.0.0.1:59043
disconnected
Server: Accepted from 127.0.0.1:59044
disconnected
Server: Accepted from 127.0.0.1:59045
disconnected
Server: Accepted from 127.0.0.1:59046
disconnected
Server: Accepted from 127.0.0.1:59047
disconnected
Server: Accepted from 127.0.0.1:59048
disconnected
Server: Accepted from 127.0.0.1:59049
disconnected
Server: Accepted from 127.0.0.1:59050
disconnected
Server: Accepted from 127.0.0.1:59052
disconnected
Server: Accepted from 127.0.0.1:59053
disconnected
Server: Accepted from 127.0.0.1:59054
disconnected
Server: Accepted from 127.0.0.1:59055
disconnected
Server: Accepted from 127.0.0.1:59057
disconnected
Server: Accepted from 127.0.0.1:59058
disconnected
Server: Accepted from 127.0.0.1:59059
disconnected
Server: Accepted from 127.0.0.1:59060
disconnected
Server: Accepted from 127.0.0.1:59062
```

**Comment by marci4** [comment]
Closing this issue as it should be solved.

Best regards,
Marcel
