### ISSUE TITLE
Reconnect doesn't work

### ISSUE THREAD

**Issue by lvca** [TooTallNate/Java-WebSocket#987]
**Describe the bug**

Once the connection has been established, I see that the onDisconnected() event is called often (by the way, why?), so I've implemented a reconnect following your guidelines.

Unfortunately, after a while, it goes into a state where it's impossible to reconnect. I see tons of messages like this:
```
com.neovisionaries.ws.client.WebSocketException: Failed to connect to '<my-host>:443': null
	at com.neovisionaries.ws.client.SocketConnector.connectSocket(SocketConnector.java:127)
	at com.neovisionaries.ws.client.SocketConnector.doConnect(SocketConnector.java:239)
	at com.neovisionaries.ws.client.SocketConnector.connect(SocketConnector.java:190)
	at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:2323)
	at mypackage.connect(WSChannelClient.java:85)
	at mypackage.WSChannelClient.reconnect(WSChannelClient.java:156)
	at mypackage.WSChannelClient$1.onDisconnected(WSChannelClient.java:80)
	at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224)
	at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3730)
	at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3696)
	at com.neovisionaries.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3663)
	at com.neovisionaries.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:80)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1343)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
	at com.neovisionaries.ws.client.SocketInitiator$SocketFuture.await(SocketInitiator.java:293)
	at com.neovisionaries.ws.client.SocketInitiator.establish(SocketInitiator.java:370)
	at com.neovisionaries.ws.client.SocketConnector.connectSocket(SocketConnector.java:115)
	... 13 more
```
**To Reproduce**

This my piece of code:
```
@Override
public void onDisconnected(WebSocket websocket, WebSocketFrame serverCloseFrame, WebSocketFrame clientCloseFrame, boolean closedByServer) {
  if (connection != null) {
    connection.sendClose();
    connection.disconnect();
    connection = null;
  }
   connection = factory.createSocket(serverURL);
  // REGISTER MY LISTENERS
  connection.connect();
  }
});
```
I've also tried the recreate, like this:

```
connection = connection.recreate();
connection.connect();
```

But doesn't work either:
```
com.neovisionaries.ws.client.WebSocketException: The current state of the WebSocket is not CREATED.
	at com.neovisionaries.ws.client.WebSocket.changeStateOnConnect(WebSocket.java:3259)
	at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:2315)
	at mypackage.WSChannelClient.connect(WSChannelClient.java:85)
	at mypackage.WSChannelClient.reconnect(WSChannelClient.java:157)
	at mypackage.WSChannelClient$1.onDisconnected(WSChannelClient.java:80)
	at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224)
	at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3730)
	at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3696)
	at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3685)
	at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539)
	at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by marci4** [comment]
Hello @lvca,
we do not provide an API like `onDisconnected`.
Please report this issue to the correspondig project!

Best regards,
Marcel

**Comment by lvca** [comment]
Sorry, I was evaluating 2 libs and actually this library works much better than the other one. Please forget this issue and congrats for the project!

**Comment by marci4** [comment]
All good :) and thx
